{{- if or (and (eq .Values.database.type "mysql") .Values.database.mysql.enabled (not .Values.database.mysql.auth.existingSecret)) (and (eq .Values.database.type "postgres") .Values.database.postgres.enabled (not .Values.database.postgres.auth.existingSecret)) (and (eq .Values.database.type "external") .Values.database.external.enabled (not .Values.database.external.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "katib.database.secretName" . }}
  namespace: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.type "mysql" }}
  {{- if .Values.database.mysql.auth.rootPassword }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.mysql.auth.rootPassword | b64enc }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  {{- if .Values.database.mysql.auth.password }}
  MYSQL_PASSWORD: {{ .Values.database.mysql.auth.password | b64enc }}
  {{- else }}
  MYSQL_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  MYSQL_USER: {{ .Values.database.mysql.auth.username | b64enc }}
  MYSQL_DATABASE: {{ .Values.database.mysql.auth.database | b64enc }}
  {{- else if eq .Values.database.type "postgres" }}
  {{- if .Values.database.postgres.auth.password }}
  POSTGRES_PASSWORD: {{ .Values.database.postgres.auth.password | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  POSTGRES_USER: {{ .Values.database.postgres.auth.username | b64enc }}
  POSTGRES_DB: {{ .Values.database.postgres.auth.database | b64enc }}
  {{- else if eq .Values.database.type "external" }}
  {{- if .Values.database.external.password }}
  DB_PASSWORD: {{ .Values.database.external.password | b64enc }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  DB_USER: {{ .Values.database.external.username | b64enc }}
  DB_NAME: {{ .Values.database.external.database | b64enc }}
  DB_HOST: {{ .Values.database.external.host | b64enc }}
  DB_PORT: {{ .Values.database.external.port | toString | b64enc }}
  {{- end }}
{{- end }} 