# coding: utf-8

"""
    Katib

    Swagger description for Katib  # noqa: E501

    OpenAPI spec version: v1alpha3-0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from kubeflow import katib
from kubeflow.katib.models.v1alpha3_file_system_path import V1alpha3FileSystemPath  # noqa: E501
from kubeflow.katib.rest import ApiException


class TestV1alpha3FileSystemPath(unittest.TestCase):
    """V1alpha3FileSystemPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha3FileSystemPath(self):
        """Test V1alpha3FileSystemPath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = katib.models.v1alpha3_file_system_path.V1alpha3FileSystemPath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
