{{- if and .Values.openshift.enabled .Values.openshift.serviceCertificates .Values.webhook.enabled }}
---
# OpenShift service serving certificate annotation
# This will be added to the webhook service to automatically provision certificates
apiVersion: v1
kind: Service
metadata:
  name: {{ include "katib.webhook.serviceName" . }}
  namespace: {{ include "katib.namespace" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "katib.webhook.secretName" . }}
    {{- with .Values.webhook.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "katib.webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "katib.controller.selectorLabels" . | nindent 4 }}
{{- end }} 