# CI values for standalone installation with PostgreSQL
# This corresponds to the katib-standalone-postgres installation profile

global:
  namespace: kubeflow
  imageTag: latest

# Controller configuration
controller:
  enabled: true
  replicas: 1
  leaderElection:
    enabled: false

# Database configuration - PostgreSQL
database:
  type: postgres
  mysql:
    enabled: false
  postgres:
    enabled: true
    persistence:
      enabled: true
      size: 1Gi  # Smaller for CI
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
  external:
    enabled: false

# DB Manager
dbManager:
  enabled: true

# UI configuration
ui:
  enabled: true

# Webhook configuration
webhook:
  enabled: true
  certManager:
    enabled: false  # Use self-signed for CI
  validating:
    enabled: true
  mutating:
    enabled: true
    podMutator:
      enabled: true

# CRDs
crds:
  install: true

# RBAC
rbac:
  create: true

# Monitoring - disabled for CI
monitoring:
  prometheus:
    enabled: false

# Istio - disabled for standalone
istio:
  enabled: false

# Security features - disabled for CI simplicity
networkPolicy:
  enabled: false

podDisruptionBudget:
  enabled: false

autoscaling:
  enabled: false

# Namespace creation
namespaceCreate:
  enabled: true 