# Copyright 2023 The Kubeflow Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for building the source code of conformance tests
FROM python:3.10-slim

ARG TARGETARCH
WORKDIR /kubeflow/katib

COPY sdk/ /kubeflow/katib/sdk/
COPY examples/ /kubeflow/katib/examples/
COPY test/ /kubeflow/katib/test/
COPY pkg/ /kubeflow/katib/pkg/

COPY conformance/run.sh .

# Add test script.
RUN chmod +x run.sh


RUN if [ "${TARGETARCH}" = "ppc64le" ]; then \
      pip install --prefer-binary -e sdk/python/v1beta1 \
        --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux/+simple/; \
    else \
      pip install --prefer-binary -e sdk/python/v1beta1; \
    fi

ENTRYPOINT [ "./run.sh" ]
