{{- if .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "katib.ui.serviceAccountName" . }}
  namespace: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.ui.serviceAccountLabels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 