---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: optuna-distribution
spec:
  objective:
    type: minimize
    goal: 0.05
    objectiveMetricName: loss
  algorithm:
    algorithmName: tpe
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "1"
        max: "5"
        step: "0.1"
        distribution: uniform
    - name: momentum
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "3"
        distribution: logUniform
    - name: epochs
      parameterType: int
      feasibleSpace:
        min: "1"
        max: "3"
        distribution: uniform
    - name: batch_size
      parameterType: int
      feasibleSpace:
        min: "32"
        max: "64"
        distribution: logUniform
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: momentum
        description: Momentum for the training model
        reference: momentum
      - name: epochs
        description: Epochs
        reference: epochs
      - name: batchSize
        description: Batch Size
        reference: batch_size
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: ghcr.io/kubeflow/katib/pytorch-mnist-cpu:latest
                command:
                  - "python3"
                  - "/opt/pytorch-mnist/mnist.py"
                  - "--epochs=${trialParameters.epochs}"
                  - "--batch-size=${trialParameters.batchSize}"
                  - "--lr=${trialParameters.learningRate}"
                  - "--momentum=${trialParameters.momentum}"
            restartPolicy: Never
