/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/katib/pkg/apis/studycontroller/v1alpha1"
	scheme "github.com/kubeflow/katib/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StudyControllersGetter has a method to return a StudyControllerInterface.
// A group's client should implement this interface.
type StudyControllersGetter interface {
	StudyControllers(namespace string) StudyControllerInterface
}

// StudyControllerInterface has methods to work with StudyController resources.
type StudyControllerInterface interface {
	Create(*v1alpha1.StudyController) (*v1alpha1.StudyController, error)
	Update(*v1alpha1.StudyController) (*v1alpha1.StudyController, error)
	UpdateStatus(*v1alpha1.StudyController) (*v1alpha1.StudyController, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StudyController, error)
	List(opts v1.ListOptions) (*v1alpha1.StudyControllerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StudyController, err error)
	StudyControllerExpansion
}

// studyControllers implements StudyControllerInterface
type studyControllers struct {
	client rest.Interface
	ns     string
}

// newStudyControllers returns a StudyControllers
func newStudyControllers(c *StudycontrollerV1alpha1Client, namespace string) *studyControllers {
	return &studyControllers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the studyController, and returns the corresponding studyController object, and an error if there is any.
func (c *studyControllers) Get(name string, options v1.GetOptions) (result *v1alpha1.StudyController, err error) {
	result = &v1alpha1.StudyController{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("studycontrollers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StudyControllers that match those selectors.
func (c *studyControllers) List(opts v1.ListOptions) (result *v1alpha1.StudyControllerList, err error) {
	result = &v1alpha1.StudyControllerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("studycontrollers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested studyControllers.
func (c *studyControllers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("studycontrollers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a studyController and creates it.  Returns the server's representation of the studyController, and an error, if there is any.
func (c *studyControllers) Create(studyController *v1alpha1.StudyController) (result *v1alpha1.StudyController, err error) {
	result = &v1alpha1.StudyController{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("studycontrollers").
		Body(studyController).
		Do().
		Into(result)
	return
}

// Update takes the representation of a studyController and updates it. Returns the server's representation of the studyController, and an error, if there is any.
func (c *studyControllers) Update(studyController *v1alpha1.StudyController) (result *v1alpha1.StudyController, err error) {
	result = &v1alpha1.StudyController{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("studycontrollers").
		Name(studyController.Name).
		Body(studyController).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *studyControllers) UpdateStatus(studyController *v1alpha1.StudyController) (result *v1alpha1.StudyController, err error) {
	result = &v1alpha1.StudyController{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("studycontrollers").
		Name(studyController.Name).
		SubResource("status").
		Body(studyController).
		Do().
		Into(result)
	return
}

// Delete takes name of the studyController and deletes it. Returns an error if one occurs.
func (c *studyControllers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("studycontrollers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *studyControllers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("studycontrollers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched studyController.
func (c *studyControllers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StudyController, err error) {
	result = &v1alpha1.StudyController{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("studycontrollers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
