---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: torch-distributed-example
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: minimize
    goal: 0.001
    objectiveMetricName: loss
  algorithm:
    algorithmName: random
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: momentum
      parameterType: double
      feasibleSpace:
        min: "0.5"
        max: "0.9"
    #- name: arg
    #  parameterType: int
    #  feasibleSpace:
    #    min: 1
    #    max: 5
  trialTemplate:
    primaryContainerName: pytorch
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: momentum
        description: Momentum for the training model
        reference: momentum
      - name: arg
        description: An additional argument for the training model
        reference: arg
    trialSpec:
      apiVersion: trainer.kubeflow.org/v1alpha1
      kind: TrainJob
      spec:
        runtimeRef:
          name: torch-distributed
        trainer:
          numNodes: 2
          image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
          command:
            - "python3"
            - "/opt/pytorch-mnist/mnist.py"
            - "--epochs=1"
            - "--lr=${trialParameters.learningRate}"
            - "--momentum=${trialParameters.momentum}"
          #image: docker.io/kubeflowkatib/pytorch-deepspeed_train_t5:latest
          #command:
          #  - "python3"
          #  - "/opt/pytorch-deepspeed/t5_llm.py"
          #  - "--arg=${trialParameters.arg}"

