// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api_v1_alpha2 is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	FeasibleSpace
	ParameterSpec
	ObjectiveSpec
	AlgorithmSetting
	EarlyStoppingSpec
	AlgorithmSpec
	NasConfig
	GraphConfig
	Operation
	ExperimentSpec
	ExperimentStatus
	Experiment
	ParameterAssignment
	Metric
	MetricLog
	Observation
	ObservationLog
	TrialSpec
	TrialStatus
	Trial
	RegisterExperimentRequest
	RegisterExperimentReply
	DeleteExperimentRequest
	DeleteExperimentReply
	GetExperimentRequest
	GetExperimentReply
	ExperimentSummary
	GetExperimentListRequest
	GetExperimentListReply
	UpdateExperimentStatusRequest
	UpdateExperimentStatusReply
	UpdateAlgorithmSpecRequest
	UpdateAlgorithmSpecReply
	RegisterTrialRequest
	RegisterTrialReply
	DeleteTrialRequest
	DeleteTrialReply
	GetTrialListRequest
	GetTrialListReply
	GetTrialRequest
	GetTrialReply
	UpdateTrialStatusRequest
	UpdateTrialStatusReply
	ReportObservationLogRequest
	ReportObservationLogReply
	GetObservationLogRequest
	GetObservationLogReply
	GetSuggestionsRequest
	GetSuggestionsReply
	ValidateAlgorithmSettingsRequest
	ValidateAlgorithmSettingsReply
*/
package api_v1_alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Types of value for HyperParameter.
type ParameterType int32

const (
	ParameterType_UNKNOWN_TYPE ParameterType = 0
	ParameterType_DOUBLE       ParameterType = 1
	ParameterType_INT          ParameterType = 2
	ParameterType_DISCRETE     ParameterType = 3
	ParameterType_CATEGORICAL  ParameterType = 4
)

var ParameterType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "DOUBLE",
	2: "INT",
	3: "DISCRETE",
	4: "CATEGORICAL",
}
var ParameterType_value = map[string]int32{
	"UNKNOWN_TYPE": 0,
	"DOUBLE":       1,
	"INT":          2,
	"DISCRETE":     3,
	"CATEGORICAL":  4,
}

func (x ParameterType) String() string {
	return proto.EnumName(ParameterType_name, int32(x))
}
func (ParameterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Direction of optimization. Minimize or Maximize.
type ObjectiveType int32

const (
	ObjectiveType_UNKNOWN  ObjectiveType = 0
	ObjectiveType_MINIMIZE ObjectiveType = 1
	ObjectiveType_MAXIMIZE ObjectiveType = 2
)

var ObjectiveType_name = map[int32]string{
	0: "UNKNOWN",
	1: "MINIMIZE",
	2: "MAXIMIZE",
}
var ObjectiveType_value = map[string]int32{
	"UNKNOWN":  0,
	"MINIMIZE": 1,
	"MAXIMIZE": 2,
}

func (x ObjectiveType) String() string {
	return proto.EnumName(ObjectiveType_name, int32(x))
}
func (ObjectiveType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ExperimentStatus_ExperimentConditionType int32

const (
	ExperimentStatus_CREATED    ExperimentStatus_ExperimentConditionType = 0
	ExperimentStatus_RUNNING    ExperimentStatus_ExperimentConditionType = 1
	ExperimentStatus_RESTARTING ExperimentStatus_ExperimentConditionType = 2
	ExperimentStatus_SUCCEEDED  ExperimentStatus_ExperimentConditionType = 3
	ExperimentStatus_FAILED     ExperimentStatus_ExperimentConditionType = 4
)

var ExperimentStatus_ExperimentConditionType_name = map[int32]string{
	0: "CREATED",
	1: "RUNNING",
	2: "RESTARTING",
	3: "SUCCEEDED",
	4: "FAILED",
}
var ExperimentStatus_ExperimentConditionType_value = map[string]int32{
	"CREATED":    0,
	"RUNNING":    1,
	"RESTARTING": 2,
	"SUCCEEDED":  3,
	"FAILED":     4,
}

func (x ExperimentStatus_ExperimentConditionType) String() string {
	return proto.EnumName(ExperimentStatus_ExperimentConditionType_name, int32(x))
}
func (ExperimentStatus_ExperimentConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type TrialStatus_TrialConditionType int32

const (
	TrialStatus_PENDING   TrialStatus_TrialConditionType = 0
	TrialStatus_RUNNING   TrialStatus_TrialConditionType = 1
	TrialStatus_COMPLETED TrialStatus_TrialConditionType = 2
	TrialStatus_KILLED    TrialStatus_TrialConditionType = 3
	TrialStatus_FAILED    TrialStatus_TrialConditionType = 4
)

var TrialStatus_TrialConditionType_name = map[int32]string{
	0: "PENDING",
	1: "RUNNING",
	2: "COMPLETED",
	3: "KILLED",
	4: "FAILED",
}
var TrialStatus_TrialConditionType_value = map[string]int32{
	"PENDING":   0,
	"RUNNING":   1,
	"COMPLETED": 2,
	"KILLED":    3,
	"FAILED":    4,
}

func (x TrialStatus_TrialConditionType) String() string {
	return proto.EnumName(TrialStatus_TrialConditionType_name, int32(x))
}
func (TrialStatus_TrialConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18, 0}
}

// *
// Feasible space for optimization.
// Int and Double type use Max/Min.
// Discrete and Categorical type use List.
type FeasibleSpace struct {
	Max  string   `protobuf:"bytes,1,opt,name=max" json:"max,omitempty"`
	Min  string   `protobuf:"bytes,2,opt,name=min" json:"min,omitempty"`
	List []string `protobuf:"bytes,3,rep,name=list" json:"list,omitempty"`
	Step string   `protobuf:"bytes,4,opt,name=step" json:"step,omitempty"`
}

func (m *FeasibleSpace) Reset()                    { *m = FeasibleSpace{} }
func (m *FeasibleSpace) String() string            { return proto.CompactTextString(m) }
func (*FeasibleSpace) ProtoMessage()               {}
func (*FeasibleSpace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FeasibleSpace) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *FeasibleSpace) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *FeasibleSpace) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *FeasibleSpace) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

// *
// Config for a Hyper parameter.
// Katib will create each Hyper parameter from this config.
type ParameterSpec struct {
	Name          string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ParameterType ParameterType  `protobuf:"varint,2,opt,name=parameter_type,json=parameterType,enum=api.v1.alpha2.ParameterType" json:"parameter_type,omitempty"`
	FeasibleSpace *FeasibleSpace `protobuf:"bytes,3,opt,name=feasible_space,json=feasibleSpace" json:"feasible_space,omitempty"`
}

func (m *ParameterSpec) Reset()                    { *m = ParameterSpec{} }
func (m *ParameterSpec) String() string            { return proto.CompactTextString(m) }
func (*ParameterSpec) ProtoMessage()               {}
func (*ParameterSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ParameterSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterSpec) GetParameterType() ParameterType {
	if m != nil {
		return m.ParameterType
	}
	return ParameterType_UNKNOWN_TYPE
}

func (m *ParameterSpec) GetFeasibleSpace() *FeasibleSpace {
	if m != nil {
		return m.FeasibleSpace
	}
	return nil
}

type ObjectiveSpec struct {
	Type                   ObjectiveType `protobuf:"varint,1,opt,name=type,enum=api.v1.alpha2.ObjectiveType" json:"type,omitempty"`
	Goal                   float32       `protobuf:"fixed32,2,opt,name=goal" json:"goal,omitempty"`
	ObjectiveMetricName    string        `protobuf:"bytes,3,opt,name=objective_metric_name,json=objectiveMetricName" json:"objective_metric_name,omitempty"`
	AdditionalMetricsNames []string      `protobuf:"bytes,4,rep,name=additional_metrics_names,json=additionalMetricsNames" json:"additional_metrics_names,omitempty"`
}

func (m *ObjectiveSpec) Reset()                    { *m = ObjectiveSpec{} }
func (m *ObjectiveSpec) String() string            { return proto.CompactTextString(m) }
func (*ObjectiveSpec) ProtoMessage()               {}
func (*ObjectiveSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ObjectiveSpec) GetType() ObjectiveType {
	if m != nil {
		return m.Type
	}
	return ObjectiveType_UNKNOWN
}

func (m *ObjectiveSpec) GetGoal() float32 {
	if m != nil {
		return m.Goal
	}
	return 0
}

func (m *ObjectiveSpec) GetObjectiveMetricName() string {
	if m != nil {
		return m.ObjectiveMetricName
	}
	return ""
}

func (m *ObjectiveSpec) GetAdditionalMetricsNames() []string {
	if m != nil {
		return m.AdditionalMetricsNames
	}
	return nil
}

type AlgorithmSetting struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *AlgorithmSetting) Reset()                    { *m = AlgorithmSetting{} }
func (m *AlgorithmSetting) String() string            { return proto.CompactTextString(m) }
func (*AlgorithmSetting) ProtoMessage()               {}
func (*AlgorithmSetting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlgorithmSetting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlgorithmSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EarlyStoppingSpec struct {
}

func (m *EarlyStoppingSpec) Reset()                    { *m = EarlyStoppingSpec{} }
func (m *EarlyStoppingSpec) String() string            { return proto.CompactTextString(m) }
func (*EarlyStoppingSpec) ProtoMessage()               {}
func (*EarlyStoppingSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AlgorithmSpec struct {
	AlgorithmName     string              `protobuf:"bytes,1,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
	AlgorithmSetting  []*AlgorithmSetting `protobuf:"bytes,2,rep,name=algorithm_setting,json=algorithmSetting" json:"algorithm_setting,omitempty"`
	EarlyStoppingSpec *EarlyStoppingSpec  `protobuf:"bytes,3,opt,name=early_stopping_spec,json=earlyStoppingSpec" json:"early_stopping_spec,omitempty"`
}

func (m *AlgorithmSpec) Reset()                    { *m = AlgorithmSpec{} }
func (m *AlgorithmSpec) String() string            { return proto.CompactTextString(m) }
func (*AlgorithmSpec) ProtoMessage()               {}
func (*AlgorithmSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AlgorithmSpec) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *AlgorithmSpec) GetAlgorithmSetting() []*AlgorithmSetting {
	if m != nil {
		return m.AlgorithmSetting
	}
	return nil
}

func (m *AlgorithmSpec) GetEarlyStoppingSpec() *EarlyStoppingSpec {
	if m != nil {
		return m.EarlyStoppingSpec
	}
	return nil
}

// *
// TODO add to AlgorithmSpec
// NasConfig contains a config of NAS job
type NasConfig struct {
	GraphConfig *GraphConfig          `protobuf:"bytes,1,opt,name=graph_config,json=graphConfig" json:"graph_config,omitempty"`
	Operations  *NasConfig_Operations `protobuf:"bytes,2,opt,name=operations" json:"operations,omitempty"`
}

func (m *NasConfig) Reset()                    { *m = NasConfig{} }
func (m *NasConfig) String() string            { return proto.CompactTextString(m) }
func (*NasConfig) ProtoMessage()               {}
func (*NasConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NasConfig) GetGraphConfig() *GraphConfig {
	if m != nil {
		return m.GraphConfig
	}
	return nil
}

func (m *NasConfig) GetOperations() *NasConfig_Operations {
	if m != nil {
		return m.Operations
	}
	return nil
}

type NasConfig_Operations struct {
	Operation []*Operation `protobuf:"bytes,1,rep,name=operation" json:"operation,omitempty"`
}

func (m *NasConfig_Operations) Reset()                    { *m = NasConfig_Operations{} }
func (m *NasConfig_Operations) String() string            { return proto.CompactTextString(m) }
func (*NasConfig_Operations) ProtoMessage()               {}
func (*NasConfig_Operations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *NasConfig_Operations) GetOperation() []*Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

// *
// GraphConfig contains a config of DAG
type GraphConfig struct {
	NumLayers  int32   `protobuf:"varint,1,opt,name=num_layers,json=numLayers" json:"num_layers,omitempty"`
	InputSize  []int32 `protobuf:"varint,2,rep,packed,name=input_size,json=inputSize" json:"input_size,omitempty"`
	OutputSize []int32 `protobuf:"varint,3,rep,packed,name=output_size,json=outputSize" json:"output_size,omitempty"`
}

func (m *GraphConfig) Reset()                    { *m = GraphConfig{} }
func (m *GraphConfig) String() string            { return proto.CompactTextString(m) }
func (*GraphConfig) ProtoMessage()               {}
func (*GraphConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GraphConfig) GetNumLayers() int32 {
	if m != nil {
		return m.NumLayers
	}
	return 0
}

func (m *GraphConfig) GetInputSize() []int32 {
	if m != nil {
		return m.InputSize
	}
	return nil
}

func (m *GraphConfig) GetOutputSize() []int32 {
	if m != nil {
		return m.OutputSize
	}
	return nil
}

// *
// Config for operations in DAG
type Operation struct {
	OperationType        string                          `protobuf:"bytes,1,opt,name=operation_type,json=operationType" json:"operation_type,omitempty"`
	ParameterAssignments *Operation_ParameterAssignments `protobuf:"bytes,2,opt,name=parameter_assignments,json=parameterAssignments" json:"parameter_assignments,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Operation) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *Operation) GetParameterAssignments() *Operation_ParameterAssignments {
	if m != nil {
		return m.ParameterAssignments
	}
	return nil
}

// *
// List of ParameterAssignment
type Operation_ParameterAssignments struct {
	Assignments []*ParameterAssignment `protobuf:"bytes,1,rep,name=assignments" json:"assignments,omitempty"`
}

func (m *Operation_ParameterAssignments) Reset()         { *m = Operation_ParameterAssignments{} }
func (m *Operation_ParameterAssignments) String() string { return proto.CompactTextString(m) }
func (*Operation_ParameterAssignments) ProtoMessage()    {}
func (*Operation_ParameterAssignments) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *Operation_ParameterAssignments) GetAssignments() []*ParameterAssignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

// *
// Spec of a Experiment. Experiment represents a single optimization run over a feasible space.
// Each Experiment contains a configuration describing the feasible space, as well as a set of Trials.
// It is assumed that objective function f(x) does not change in the course of a Experiment.
type ExperimentSpec struct {
	Parameters           []*ParameterSpec `protobuf:"bytes,1,rep,name=parameters" json:"parameters,omitempty"`
	Objective            *ObjectiveSpec   `protobuf:"bytes,2,opt,name=objective" json:"objective,omitempty"`
	Algorithm            *AlgorithmSpec   `protobuf:"bytes,3,opt,name=algorithm" json:"algorithm,omitempty"`
	TrialTemplate        string           `protobuf:"bytes,4,opt,name=trial_template,json=trialTemplate" json:"trial_template,omitempty"`
	ParallelTrialCount   int32            `protobuf:"varint,5,opt,name=parallel_trial_count,json=parallelTrialCount" json:"parallel_trial_count,omitempty"`
	MaxTrialCount        int32            `protobuf:"varint,6,opt,name=max_trial_count,json=maxTrialCount" json:"max_trial_count,omitempty"`
	MetricsCollectorType string           `protobuf:"bytes,7,opt,name=metrics_collector_type,json=metricsCollectorType" json:"metrics_collector_type,omitempty"`
}

func (m *ExperimentSpec) Reset()                    { *m = ExperimentSpec{} }
func (m *ExperimentSpec) String() string            { return proto.CompactTextString(m) }
func (*ExperimentSpec) ProtoMessage()               {}
func (*ExperimentSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ExperimentSpec) GetParameters() []*ParameterSpec {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExperimentSpec) GetObjective() *ObjectiveSpec {
	if m != nil {
		return m.Objective
	}
	return nil
}

func (m *ExperimentSpec) GetAlgorithm() *AlgorithmSpec {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *ExperimentSpec) GetTrialTemplate() string {
	if m != nil {
		return m.TrialTemplate
	}
	return ""
}

func (m *ExperimentSpec) GetParallelTrialCount() int32 {
	if m != nil {
		return m.ParallelTrialCount
	}
	return 0
}

func (m *ExperimentSpec) GetMaxTrialCount() int32 {
	if m != nil {
		return m.MaxTrialCount
	}
	return 0
}

func (m *ExperimentSpec) GetMetricsCollectorType() string {
	if m != nil {
		return m.MetricsCollectorType
	}
	return ""
}

type ExperimentStatus struct {
	StartTime      string                                   `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	CompletionTime string                                   `protobuf:"bytes,2,opt,name=completion_time,json=completionTime" json:"completion_time,omitempty"`
	Condition      ExperimentStatus_ExperimentConditionType `protobuf:"varint,3,opt,name=condition,enum=api.v1.alpha2.ExperimentStatus_ExperimentConditionType" json:"condition,omitempty"`
}

func (m *ExperimentStatus) Reset()                    { *m = ExperimentStatus{} }
func (m *ExperimentStatus) String() string            { return proto.CompactTextString(m) }
func (*ExperimentStatus) ProtoMessage()               {}
func (*ExperimentStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ExperimentStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *ExperimentStatus) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *ExperimentStatus) GetCondition() ExperimentStatus_ExperimentConditionType {
	if m != nil {
		return m.Condition
	}
	return ExperimentStatus_CREATED
}

type Experiment struct {
	Name             string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ExperimentSpec   *ExperimentSpec   `protobuf:"bytes,2,opt,name=experiment_spec,json=experimentSpec" json:"experiment_spec,omitempty"`
	ExperimentStatus *ExperimentStatus `protobuf:"bytes,3,opt,name=experiment_status,json=experimentStatus" json:"experiment_status,omitempty"`
}

func (m *Experiment) Reset()                    { *m = Experiment{} }
func (m *Experiment) String() string            { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()               {}
func (*Experiment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Experiment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Experiment) GetExperimentSpec() *ExperimentSpec {
	if m != nil {
		return m.ExperimentSpec
	}
	return nil
}

func (m *Experiment) GetExperimentStatus() *ExperimentStatus {
	if m != nil {
		return m.ExperimentStatus
	}
	return nil
}

type ParameterAssignment struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ParameterAssignment) Reset()                    { *m = ParameterAssignment{} }
func (m *ParameterAssignment) String() string            { return proto.CompactTextString(m) }
func (*ParameterAssignment) ProtoMessage()               {}
func (*ParameterAssignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ParameterAssignment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterAssignment) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Metric struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MetricLog struct {
	TimeStamp string  `protobuf:"bytes,1,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Metric    *Metric `protobuf:"bytes,2,opt,name=metric" json:"metric,omitempty"`
}

func (m *MetricLog) Reset()                    { *m = MetricLog{} }
func (m *MetricLog) String() string            { return proto.CompactTextString(m) }
func (*MetricLog) ProtoMessage()               {}
func (*MetricLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MetricLog) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *MetricLog) GetMetric() *Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

type Observation struct {
	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *Observation) Reset()                    { *m = Observation{} }
func (m *Observation) String() string            { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()               {}
func (*Observation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Observation) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ObservationLog struct {
	Metriclogs []*MetricLog `protobuf:"bytes,1,rep,name=metriclogs" json:"metriclogs,omitempty"`
}

func (m *ObservationLog) Reset()                    { *m = ObservationLog{} }
func (m *ObservationLog) String() string            { return proto.CompactTextString(m) }
func (*ObservationLog) ProtoMessage()               {}
func (*ObservationLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ObservationLog) GetMetriclogs() []*MetricLog {
	if m != nil {
		return m.Metriclogs
	}
	return nil
}

type TrialSpec struct {
	ExperimentName       string                 `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	ParameterAssignments []*ParameterAssignment `protobuf:"bytes,2,rep,name=parameter_assignments,json=parameterAssignments" json:"parameter_assignments,omitempty"`
	RunSpec              string                 `protobuf:"bytes,3,opt,name=run_spec,json=runSpec" json:"run_spec,omitempty"`
}

func (m *TrialSpec) Reset()                    { *m = TrialSpec{} }
func (m *TrialSpec) String() string            { return proto.CompactTextString(m) }
func (*TrialSpec) ProtoMessage()               {}
func (*TrialSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TrialSpec) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *TrialSpec) GetParameterAssignments() []*ParameterAssignment {
	if m != nil {
		return m.ParameterAssignments
	}
	return nil
}

func (m *TrialSpec) GetRunSpec() string {
	if m != nil {
		return m.RunSpec
	}
	return ""
}

type TrialStatus struct {
	StartTime      string                         `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	CompletionTime string                         `protobuf:"bytes,2,opt,name=completion_time,json=completionTime" json:"completion_time,omitempty"`
	Condition      TrialStatus_TrialConditionType `protobuf:"varint,3,opt,name=condition,enum=api.v1.alpha2.TrialStatus_TrialConditionType" json:"condition,omitempty"`
	Observation    *Observation                   `protobuf:"bytes,4,opt,name=observation" json:"observation,omitempty"`
}

func (m *TrialStatus) Reset()                    { *m = TrialStatus{} }
func (m *TrialStatus) String() string            { return proto.CompactTextString(m) }
func (*TrialStatus) ProtoMessage()               {}
func (*TrialStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TrialStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TrialStatus) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *TrialStatus) GetCondition() TrialStatus_TrialConditionType {
	if m != nil {
		return m.Condition
	}
	return TrialStatus_PENDING
}

func (m *TrialStatus) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

type Trial struct {
	Name   string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spec   *TrialSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status *TrialStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Trial) Reset()                    { *m = Trial{} }
func (m *Trial) String() string            { return proto.CompactTextString(m) }
func (*Trial) ProtoMessage()               {}
func (*Trial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Trial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trial) GetSpec() *TrialSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Trial) GetStatus() *TrialStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RegisterExperimentRequest struct {
	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment" json:"experiment,omitempty"`
}

func (m *RegisterExperimentRequest) Reset()                    { *m = RegisterExperimentRequest{} }
func (m *RegisterExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterExperimentRequest) ProtoMessage()               {}
func (*RegisterExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RegisterExperimentRequest) GetExperiment() *Experiment {
	if m != nil {
		return m.Experiment
	}
	return nil
}

type RegisterExperimentReply struct {
}

func (m *RegisterExperimentReply) Reset()                    { *m = RegisterExperimentReply{} }
func (m *RegisterExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterExperimentReply) ProtoMessage()               {}
func (*RegisterExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type DeleteExperimentRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
}

func (m *DeleteExperimentRequest) Reset()                    { *m = DeleteExperimentRequest{} }
func (m *DeleteExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteExperimentRequest) ProtoMessage()               {}
func (*DeleteExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeleteExperimentRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type DeleteExperimentReply struct {
}

func (m *DeleteExperimentReply) Reset()                    { *m = DeleteExperimentReply{} }
func (m *DeleteExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteExperimentReply) ProtoMessage()               {}
func (*DeleteExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetExperimentRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
}

func (m *GetExperimentRequest) Reset()                    { *m = GetExperimentRequest{} }
func (m *GetExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentRequest) ProtoMessage()               {}
func (*GetExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetExperimentRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type GetExperimentReply struct {
	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment" json:"experiment,omitempty"`
}

func (m *GetExperimentReply) Reset()                    { *m = GetExperimentReply{} }
func (m *GetExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentReply) ProtoMessage()               {}
func (*GetExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetExperimentReply) GetExperiment() *Experiment {
	if m != nil {
		return m.Experiment
	}
	return nil
}

type ExperimentSummary struct {
	ExperimentName string            `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	Status         *ExperimentStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ExperimentSummary) Reset()                    { *m = ExperimentSummary{} }
func (m *ExperimentSummary) String() string            { return proto.CompactTextString(m) }
func (*ExperimentSummary) ProtoMessage()               {}
func (*ExperimentSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ExperimentSummary) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *ExperimentSummary) GetStatus() *ExperimentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetExperimentListRequest struct {
}

func (m *GetExperimentListRequest) Reset()                    { *m = GetExperimentListRequest{} }
func (m *GetExperimentListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentListRequest) ProtoMessage()               {}
func (*GetExperimentListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type GetExperimentListReply struct {
	ExperimentSummaries []*ExperimentSummary `protobuf:"bytes,1,rep,name=experiment_summaries,json=experimentSummaries" json:"experiment_summaries,omitempty"`
}

func (m *GetExperimentListReply) Reset()                    { *m = GetExperimentListReply{} }
func (m *GetExperimentListReply) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentListReply) ProtoMessage()               {}
func (*GetExperimentListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *GetExperimentListReply) GetExperimentSummaries() []*ExperimentSummary {
	if m != nil {
		return m.ExperimentSummaries
	}
	return nil
}

type UpdateExperimentStatusRequest struct {
	ExperimentName string            `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	NewStatus      *ExperimentStatus `protobuf:"bytes,2,opt,name=new_status,json=newStatus" json:"new_status,omitempty"`
}

func (m *UpdateExperimentStatusRequest) Reset()                    { *m = UpdateExperimentStatusRequest{} }
func (m *UpdateExperimentStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateExperimentStatusRequest) ProtoMessage()               {}
func (*UpdateExperimentStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UpdateExperimentStatusRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *UpdateExperimentStatusRequest) GetNewStatus() *ExperimentStatus {
	if m != nil {
		return m.NewStatus
	}
	return nil
}

type UpdateExperimentStatusReply struct {
}

func (m *UpdateExperimentStatusReply) Reset()                    { *m = UpdateExperimentStatusReply{} }
func (m *UpdateExperimentStatusReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateExperimentStatusReply) ProtoMessage()               {}
func (*UpdateExperimentStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type UpdateAlgorithmSpecRequest struct {
	ExperimentName   string         `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	NewAlgorithmSpec *AlgorithmSpec `protobuf:"bytes,2,opt,name=new_algorithm_spec,json=newAlgorithmSpec" json:"new_algorithm_spec,omitempty"`
}

func (m *UpdateAlgorithmSpecRequest) Reset()                    { *m = UpdateAlgorithmSpecRequest{} }
func (m *UpdateAlgorithmSpecRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAlgorithmSpecRequest) ProtoMessage()               {}
func (*UpdateAlgorithmSpecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *UpdateAlgorithmSpecRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *UpdateAlgorithmSpecRequest) GetNewAlgorithmSpec() *AlgorithmSpec {
	if m != nil {
		return m.NewAlgorithmSpec
	}
	return nil
}

type UpdateAlgorithmSpecReply struct {
}

func (m *UpdateAlgorithmSpecReply) Reset()                    { *m = UpdateAlgorithmSpecReply{} }
func (m *UpdateAlgorithmSpecReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateAlgorithmSpecReply) ProtoMessage()               {}
func (*UpdateAlgorithmSpecReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type RegisterTrialRequest struct {
	Trial *Trial `protobuf:"bytes,1,opt,name=trial" json:"trial,omitempty"`
}

func (m *RegisterTrialRequest) Reset()                    { *m = RegisterTrialRequest{} }
func (m *RegisterTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterTrialRequest) ProtoMessage()               {}
func (*RegisterTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *RegisterTrialRequest) GetTrial() *Trial {
	if m != nil {
		return m.Trial
	}
	return nil
}

type RegisterTrialReply struct {
}

func (m *RegisterTrialReply) Reset()                    { *m = RegisterTrialReply{} }
func (m *RegisterTrialReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterTrialReply) ProtoMessage()               {}
func (*RegisterTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type DeleteTrialRequest struct {
	TrialName string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
}

func (m *DeleteTrialRequest) Reset()                    { *m = DeleteTrialRequest{} }
func (m *DeleteTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTrialRequest) ProtoMessage()               {}
func (*DeleteTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *DeleteTrialRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

type DeleteTrialReply struct {
}

func (m *DeleteTrialReply) Reset()                    { *m = DeleteTrialReply{} }
func (m *DeleteTrialReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteTrialReply) ProtoMessage()               {}
func (*DeleteTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type GetTrialListRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	StartTime      string `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime        string `protobuf:"bytes,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Filter         string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
}

func (m *GetTrialListRequest) Reset()                    { *m = GetTrialListRequest{} }
func (m *GetTrialListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTrialListRequest) ProtoMessage()               {}
func (*GetTrialListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *GetTrialListRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *GetTrialListRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetTrialListRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetTrialListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type GetTrialListReply struct {
	Trials []*Trial `protobuf:"bytes,1,rep,name=trials" json:"trials,omitempty"`
}

func (m *GetTrialListReply) Reset()                    { *m = GetTrialListReply{} }
func (m *GetTrialListReply) String() string            { return proto.CompactTextString(m) }
func (*GetTrialListReply) ProtoMessage()               {}
func (*GetTrialListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *GetTrialListReply) GetTrials() []*Trial {
	if m != nil {
		return m.Trials
	}
	return nil
}

type GetTrialRequest struct {
	TrialName string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
}

func (m *GetTrialRequest) Reset()                    { *m = GetTrialRequest{} }
func (m *GetTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTrialRequest) ProtoMessage()               {}
func (*GetTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *GetTrialRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

type GetTrialReply struct {
	Trial *Trial `protobuf:"bytes,1,opt,name=trial" json:"trial,omitempty"`
}

func (m *GetTrialReply) Reset()                    { *m = GetTrialReply{} }
func (m *GetTrialReply) String() string            { return proto.CompactTextString(m) }
func (*GetTrialReply) ProtoMessage()               {}
func (*GetTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *GetTrialReply) GetTrial() *Trial {
	if m != nil {
		return m.Trial
	}
	return nil
}

type UpdateTrialStatusRequest struct {
	TrialName string       `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
	NewStatus *TrialStatus `protobuf:"bytes,2,opt,name=new_status,json=newStatus" json:"new_status,omitempty"`
}

func (m *UpdateTrialStatusRequest) Reset()                    { *m = UpdateTrialStatusRequest{} }
func (m *UpdateTrialStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTrialStatusRequest) ProtoMessage()               {}
func (*UpdateTrialStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *UpdateTrialStatusRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

func (m *UpdateTrialStatusRequest) GetNewStatus() *TrialStatus {
	if m != nil {
		return m.NewStatus
	}
	return nil
}

type UpdateTrialStatusReply struct {
}

func (m *UpdateTrialStatusReply) Reset()                    { *m = UpdateTrialStatusReply{} }
func (m *UpdateTrialStatusReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateTrialStatusReply) ProtoMessage()               {}
func (*UpdateTrialStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

type ReportObservationLogRequest struct {
	TrialName      string          `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
	ObservationLog *ObservationLog `protobuf:"bytes,2,opt,name=observation_log,json=observationLog" json:"observation_log,omitempty"`
}

func (m *ReportObservationLogRequest) Reset()                    { *m = ReportObservationLogRequest{} }
func (m *ReportObservationLogRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportObservationLogRequest) ProtoMessage()               {}
func (*ReportObservationLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *ReportObservationLogRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

func (m *ReportObservationLogRequest) GetObservationLog() *ObservationLog {
	if m != nil {
		return m.ObservationLog
	}
	return nil
}

type ReportObservationLogReply struct {
}

func (m *ReportObservationLogReply) Reset()                    { *m = ReportObservationLogReply{} }
func (m *ReportObservationLogReply) String() string            { return proto.CompactTextString(m) }
func (*ReportObservationLogReply) ProtoMessage()               {}
func (*ReportObservationLogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type GetObservationLogRequest struct {
	TrialName string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
}

func (m *GetObservationLogRequest) Reset()                    { *m = GetObservationLogRequest{} }
func (m *GetObservationLogRequest) String() string            { return proto.CompactTextString(m) }
func (*GetObservationLogRequest) ProtoMessage()               {}
func (*GetObservationLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *GetObservationLogRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

type GetObservationLogReply struct {
	ObservationLog *ObservationLog `protobuf:"bytes,1,opt,name=observation_log,json=observationLog" json:"observation_log,omitempty"`
}

func (m *GetObservationLogReply) Reset()                    { *m = GetObservationLogReply{} }
func (m *GetObservationLogReply) String() string            { return proto.CompactTextString(m) }
func (*GetObservationLogReply) ProtoMessage()               {}
func (*GetObservationLogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *GetObservationLogReply) GetObservationLog() *ObservationLog {
	if m != nil {
		return m.ObservationLog
	}
	return nil
}

type GetSuggestionsRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	AlgorithmName  string `protobuf:"bytes,2,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
	RequestNumber  int32  `protobuf:"varint,3,opt,name=request_number,json=requestNumber" json:"request_number,omitempty"`
}

func (m *GetSuggestionsRequest) Reset()                    { *m = GetSuggestionsRequest{} }
func (m *GetSuggestionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestionsRequest) ProtoMessage()               {}
func (*GetSuggestionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *GetSuggestionsRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *GetSuggestionsRequest) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *GetSuggestionsRequest) GetRequestNumber() int32 {
	if m != nil {
		return m.RequestNumber
	}
	return 0
}

type GetSuggestionsReply struct {
	Trials []*Trial `protobuf:"bytes,1,rep,name=trials" json:"trials,omitempty"`
}

func (m *GetSuggestionsReply) Reset()                    { *m = GetSuggestionsReply{} }
func (m *GetSuggestionsReply) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestionsReply) ProtoMessage()               {}
func (*GetSuggestionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *GetSuggestionsReply) GetTrials() []*Trial {
	if m != nil {
		return m.Trials
	}
	return nil
}

type ValidateAlgorithmSettingsRequest struct {
	ExperimentSpec *ExperimentSpec `protobuf:"bytes,1,opt,name=experiment_spec,json=experimentSpec" json:"experiment_spec,omitempty"`
	AlgorithmName  string          `protobuf:"bytes,2,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
}

func (m *ValidateAlgorithmSettingsRequest) Reset()         { *m = ValidateAlgorithmSettingsRequest{} }
func (m *ValidateAlgorithmSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateAlgorithmSettingsRequest) ProtoMessage()    {}
func (*ValidateAlgorithmSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{49}
}

func (m *ValidateAlgorithmSettingsRequest) GetExperimentSpec() *ExperimentSpec {
	if m != nil {
		return m.ExperimentSpec
	}
	return nil
}

func (m *ValidateAlgorithmSettingsRequest) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

// *
// Return INVALID_ARGUMENT Error if Algorithm Settings are not Valid
type ValidateAlgorithmSettingsReply struct {
}

func (m *ValidateAlgorithmSettingsReply) Reset()                    { *m = ValidateAlgorithmSettingsReply{} }
func (m *ValidateAlgorithmSettingsReply) String() string            { return proto.CompactTextString(m) }
func (*ValidateAlgorithmSettingsReply) ProtoMessage()               {}
func (*ValidateAlgorithmSettingsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func init() {
	proto.RegisterType((*FeasibleSpace)(nil), "api.v1.alpha2.FeasibleSpace")
	proto.RegisterType((*ParameterSpec)(nil), "api.v1.alpha2.ParameterSpec")
	proto.RegisterType((*ObjectiveSpec)(nil), "api.v1.alpha2.ObjectiveSpec")
	proto.RegisterType((*AlgorithmSetting)(nil), "api.v1.alpha2.AlgorithmSetting")
	proto.RegisterType((*EarlyStoppingSpec)(nil), "api.v1.alpha2.EarlyStoppingSpec")
	proto.RegisterType((*AlgorithmSpec)(nil), "api.v1.alpha2.AlgorithmSpec")
	proto.RegisterType((*NasConfig)(nil), "api.v1.alpha2.NasConfig")
	proto.RegisterType((*NasConfig_Operations)(nil), "api.v1.alpha2.NasConfig.Operations")
	proto.RegisterType((*GraphConfig)(nil), "api.v1.alpha2.GraphConfig")
	proto.RegisterType((*Operation)(nil), "api.v1.alpha2.Operation")
	proto.RegisterType((*Operation_ParameterAssignments)(nil), "api.v1.alpha2.Operation.ParameterAssignments")
	proto.RegisterType((*ExperimentSpec)(nil), "api.v1.alpha2.ExperimentSpec")
	proto.RegisterType((*ExperimentStatus)(nil), "api.v1.alpha2.ExperimentStatus")
	proto.RegisterType((*Experiment)(nil), "api.v1.alpha2.Experiment")
	proto.RegisterType((*ParameterAssignment)(nil), "api.v1.alpha2.ParameterAssignment")
	proto.RegisterType((*Metric)(nil), "api.v1.alpha2.Metric")
	proto.RegisterType((*MetricLog)(nil), "api.v1.alpha2.MetricLog")
	proto.RegisterType((*Observation)(nil), "api.v1.alpha2.Observation")
	proto.RegisterType((*ObservationLog)(nil), "api.v1.alpha2.ObservationLog")
	proto.RegisterType((*TrialSpec)(nil), "api.v1.alpha2.TrialSpec")
	proto.RegisterType((*TrialStatus)(nil), "api.v1.alpha2.TrialStatus")
	proto.RegisterType((*Trial)(nil), "api.v1.alpha2.Trial")
	proto.RegisterType((*RegisterExperimentRequest)(nil), "api.v1.alpha2.RegisterExperimentRequest")
	proto.RegisterType((*RegisterExperimentReply)(nil), "api.v1.alpha2.RegisterExperimentReply")
	proto.RegisterType((*DeleteExperimentRequest)(nil), "api.v1.alpha2.DeleteExperimentRequest")
	proto.RegisterType((*DeleteExperimentReply)(nil), "api.v1.alpha2.DeleteExperimentReply")
	proto.RegisterType((*GetExperimentRequest)(nil), "api.v1.alpha2.GetExperimentRequest")
	proto.RegisterType((*GetExperimentReply)(nil), "api.v1.alpha2.GetExperimentReply")
	proto.RegisterType((*ExperimentSummary)(nil), "api.v1.alpha2.ExperimentSummary")
	proto.RegisterType((*GetExperimentListRequest)(nil), "api.v1.alpha2.GetExperimentListRequest")
	proto.RegisterType((*GetExperimentListReply)(nil), "api.v1.alpha2.GetExperimentListReply")
	proto.RegisterType((*UpdateExperimentStatusRequest)(nil), "api.v1.alpha2.UpdateExperimentStatusRequest")
	proto.RegisterType((*UpdateExperimentStatusReply)(nil), "api.v1.alpha2.UpdateExperimentStatusReply")
	proto.RegisterType((*UpdateAlgorithmSpecRequest)(nil), "api.v1.alpha2.UpdateAlgorithmSpecRequest")
	proto.RegisterType((*UpdateAlgorithmSpecReply)(nil), "api.v1.alpha2.UpdateAlgorithmSpecReply")
	proto.RegisterType((*RegisterTrialRequest)(nil), "api.v1.alpha2.RegisterTrialRequest")
	proto.RegisterType((*RegisterTrialReply)(nil), "api.v1.alpha2.RegisterTrialReply")
	proto.RegisterType((*DeleteTrialRequest)(nil), "api.v1.alpha2.DeleteTrialRequest")
	proto.RegisterType((*DeleteTrialReply)(nil), "api.v1.alpha2.DeleteTrialReply")
	proto.RegisterType((*GetTrialListRequest)(nil), "api.v1.alpha2.GetTrialListRequest")
	proto.RegisterType((*GetTrialListReply)(nil), "api.v1.alpha2.GetTrialListReply")
	proto.RegisterType((*GetTrialRequest)(nil), "api.v1.alpha2.GetTrialRequest")
	proto.RegisterType((*GetTrialReply)(nil), "api.v1.alpha2.GetTrialReply")
	proto.RegisterType((*UpdateTrialStatusRequest)(nil), "api.v1.alpha2.UpdateTrialStatusRequest")
	proto.RegisterType((*UpdateTrialStatusReply)(nil), "api.v1.alpha2.UpdateTrialStatusReply")
	proto.RegisterType((*ReportObservationLogRequest)(nil), "api.v1.alpha2.ReportObservationLogRequest")
	proto.RegisterType((*ReportObservationLogReply)(nil), "api.v1.alpha2.ReportObservationLogReply")
	proto.RegisterType((*GetObservationLogRequest)(nil), "api.v1.alpha2.GetObservationLogRequest")
	proto.RegisterType((*GetObservationLogReply)(nil), "api.v1.alpha2.GetObservationLogReply")
	proto.RegisterType((*GetSuggestionsRequest)(nil), "api.v1.alpha2.GetSuggestionsRequest")
	proto.RegisterType((*GetSuggestionsReply)(nil), "api.v1.alpha2.GetSuggestionsReply")
	proto.RegisterType((*ValidateAlgorithmSettingsRequest)(nil), "api.v1.alpha2.ValidateAlgorithmSettingsRequest")
	proto.RegisterType((*ValidateAlgorithmSettingsReply)(nil), "api.v1.alpha2.ValidateAlgorithmSettingsReply")
	proto.RegisterEnum("api.v1.alpha2.ParameterType", ParameterType_name, ParameterType_value)
	proto.RegisterEnum("api.v1.alpha2.ObjectiveType", ObjectiveType_name, ObjectiveType_value)
	proto.RegisterEnum("api.v1.alpha2.ExperimentStatus_ExperimentConditionType", ExperimentStatus_ExperimentConditionType_name, ExperimentStatus_ExperimentConditionType_value)
	proto.RegisterEnum("api.v1.alpha2.TrialStatus_TrialConditionType", TrialStatus_TrialConditionType_name, TrialStatus_TrialConditionType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	// *
	// Register a Experiment to DB.
	RegisterExperiment(ctx context.Context, in *RegisterExperimentRequest, opts ...grpc.CallOption) (*RegisterExperimentReply, error)
	// *
	// Delete a Experiment from DB by name.
	DeleteExperiment(ctx context.Context, in *DeleteExperimentRequest, opts ...grpc.CallOption) (*DeleteExperimentReply, error)
	// *
	// Get a Experiment from DB by name.
	GetExperiment(ctx context.Context, in *GetExperimentRequest, opts ...grpc.CallOption) (*GetExperimentReply, error)
	// *
	// Get a summary list of Experiment from DB.
	// The summary includes name and condition.
	GetExperimentList(ctx context.Context, in *GetExperimentListRequest, opts ...grpc.CallOption) (*GetExperimentListReply, error)
	// *
	// Update Status of a experiment.
	UpdateExperimentStatus(ctx context.Context, in *UpdateExperimentStatusRequest, opts ...grpc.CallOption) (*UpdateExperimentStatusReply, error)
	// *
	// Update AlgorithmParameter of a experiment.
	UpdateAlgorithmSpec(ctx context.Context, in *UpdateAlgorithmSpecRequest, opts ...grpc.CallOption) (*UpdateAlgorithmSpecReply, error)
	// *
	// Register a Trial to DB.
	// ID will be filled by manager automatically.
	RegisterTrial(ctx context.Context, in *RegisterTrialRequest, opts ...grpc.CallOption) (*RegisterTrialReply, error)
	// *
	// Delete a Trial from DB by ID.
	DeleteTrial(ctx context.Context, in *DeleteTrialRequest, opts ...grpc.CallOption) (*DeleteTrialReply, error)
	// *
	// Get a list of Trial from DB by name of a Experiment.
	GetTrialList(ctx context.Context, in *GetTrialListRequest, opts ...grpc.CallOption) (*GetTrialListReply, error)
	// *
	// Get a Trial from DB by ID of Trial.
	GetTrial(ctx context.Context, in *GetTrialRequest, opts ...grpc.CallOption) (*GetTrialReply, error)
	// *
	// Update Status of a trial.
	UpdateTrialStatus(ctx context.Context, in *UpdateTrialStatusRequest, opts ...grpc.CallOption) (*UpdateTrialStatusReply, error)
	// *
	// Report a log of Observations for a Trial.
	// The log consists of timestamp and value of metric.
	// Katib store every log of metrics.
	// You can see accuracy curve or other metric logs on UI.
	ReportObservationLog(ctx context.Context, in *ReportObservationLogRequest, opts ...grpc.CallOption) (*ReportObservationLogReply, error)
	// *
	// Get all log of Observations for a Trial.
	GetObservationLog(ctx context.Context, in *GetObservationLogRequest, opts ...grpc.CallOption) (*GetObservationLogReply, error)
	// *
	// Get Suggestions from a Suggestion service.
	GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error)
	// *
	// Validate AlgorithmSettings in an Experiment.
	// Suggestion service should return INVALID_ARGUMENT Error when the parameter is invalid
	ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) RegisterExperiment(ctx context.Context, in *RegisterExperimentRequest, opts ...grpc.CallOption) (*RegisterExperimentReply, error) {
	out := new(RegisterExperimentReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/RegisterExperiment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteExperiment(ctx context.Context, in *DeleteExperimentRequest, opts ...grpc.CallOption) (*DeleteExperimentReply, error) {
	out := new(DeleteExperimentReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/DeleteExperiment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetExperiment(ctx context.Context, in *GetExperimentRequest, opts ...grpc.CallOption) (*GetExperimentReply, error) {
	out := new(GetExperimentReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetExperiment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetExperimentList(ctx context.Context, in *GetExperimentListRequest, opts ...grpc.CallOption) (*GetExperimentListReply, error) {
	out := new(GetExperimentListReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetExperimentList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateExperimentStatus(ctx context.Context, in *UpdateExperimentStatusRequest, opts ...grpc.CallOption) (*UpdateExperimentStatusReply, error) {
	out := new(UpdateExperimentStatusReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/UpdateExperimentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateAlgorithmSpec(ctx context.Context, in *UpdateAlgorithmSpecRequest, opts ...grpc.CallOption) (*UpdateAlgorithmSpecReply, error) {
	out := new(UpdateAlgorithmSpecReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/UpdateAlgorithmSpec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) RegisterTrial(ctx context.Context, in *RegisterTrialRequest, opts ...grpc.CallOption) (*RegisterTrialReply, error) {
	out := new(RegisterTrialReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/RegisterTrial", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteTrial(ctx context.Context, in *DeleteTrialRequest, opts ...grpc.CallOption) (*DeleteTrialReply, error) {
	out := new(DeleteTrialReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/DeleteTrial", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetTrialList(ctx context.Context, in *GetTrialListRequest, opts ...grpc.CallOption) (*GetTrialListReply, error) {
	out := new(GetTrialListReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetTrialList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetTrial(ctx context.Context, in *GetTrialRequest, opts ...grpc.CallOption) (*GetTrialReply, error) {
	out := new(GetTrialReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetTrial", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateTrialStatus(ctx context.Context, in *UpdateTrialStatusRequest, opts ...grpc.CallOption) (*UpdateTrialStatusReply, error) {
	out := new(UpdateTrialStatusReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/UpdateTrialStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ReportObservationLog(ctx context.Context, in *ReportObservationLogRequest, opts ...grpc.CallOption) (*ReportObservationLogReply, error) {
	out := new(ReportObservationLogReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/ReportObservationLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetObservationLog(ctx context.Context, in *GetObservationLogRequest, opts ...grpc.CallOption) (*GetObservationLogReply, error) {
	out := new(GetObservationLogReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetObservationLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error) {
	out := new(GetSuggestionsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetSuggestions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error) {
	out := new(ValidateAlgorithmSettingsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/ValidateAlgorithmSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	// *
	// Register a Experiment to DB.
	RegisterExperiment(context.Context, *RegisterExperimentRequest) (*RegisterExperimentReply, error)
	// *
	// Delete a Experiment from DB by name.
	DeleteExperiment(context.Context, *DeleteExperimentRequest) (*DeleteExperimentReply, error)
	// *
	// Get a Experiment from DB by name.
	GetExperiment(context.Context, *GetExperimentRequest) (*GetExperimentReply, error)
	// *
	// Get a summary list of Experiment from DB.
	// The summary includes name and condition.
	GetExperimentList(context.Context, *GetExperimentListRequest) (*GetExperimentListReply, error)
	// *
	// Update Status of a experiment.
	UpdateExperimentStatus(context.Context, *UpdateExperimentStatusRequest) (*UpdateExperimentStatusReply, error)
	// *
	// Update AlgorithmParameter of a experiment.
	UpdateAlgorithmSpec(context.Context, *UpdateAlgorithmSpecRequest) (*UpdateAlgorithmSpecReply, error)
	// *
	// Register a Trial to DB.
	// ID will be filled by manager automatically.
	RegisterTrial(context.Context, *RegisterTrialRequest) (*RegisterTrialReply, error)
	// *
	// Delete a Trial from DB by ID.
	DeleteTrial(context.Context, *DeleteTrialRequest) (*DeleteTrialReply, error)
	// *
	// Get a list of Trial from DB by name of a Experiment.
	GetTrialList(context.Context, *GetTrialListRequest) (*GetTrialListReply, error)
	// *
	// Get a Trial from DB by ID of Trial.
	GetTrial(context.Context, *GetTrialRequest) (*GetTrialReply, error)
	// *
	// Update Status of a trial.
	UpdateTrialStatus(context.Context, *UpdateTrialStatusRequest) (*UpdateTrialStatusReply, error)
	// *
	// Report a log of Observations for a Trial.
	// The log consists of timestamp and value of metric.
	// Katib store every log of metrics.
	// You can see accuracy curve or other metric logs on UI.
	ReportObservationLog(context.Context, *ReportObservationLogRequest) (*ReportObservationLogReply, error)
	// *
	// Get all log of Observations for a Trial.
	GetObservationLog(context.Context, *GetObservationLogRequest) (*GetObservationLogReply, error)
	// *
	// Get Suggestions from a Suggestion service.
	GetSuggestions(context.Context, *GetSuggestionsRequest) (*GetSuggestionsReply, error)
	// *
	// Validate AlgorithmSettings in an Experiment.
	// Suggestion service should return INVALID_ARGUMENT Error when the parameter is invalid
	ValidateAlgorithmSettings(context.Context, *ValidateAlgorithmSettingsRequest) (*ValidateAlgorithmSettingsReply, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_RegisterExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).RegisterExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/RegisterExperiment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).RegisterExperiment(ctx, req.(*RegisterExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/DeleteExperiment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteExperiment(ctx, req.(*DeleteExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetExperiment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetExperiment(ctx, req.(*GetExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetExperimentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetExperimentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetExperimentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetExperimentList(ctx, req.(*GetExperimentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateExperimentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExperimentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateExperimentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/UpdateExperimentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateExperimentStatus(ctx, req.(*UpdateExperimentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateAlgorithmSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlgorithmSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateAlgorithmSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/UpdateAlgorithmSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateAlgorithmSpec(ctx, req.(*UpdateAlgorithmSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_RegisterTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).RegisterTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/RegisterTrial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).RegisterTrial(ctx, req.(*RegisterTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/DeleteTrial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteTrial(ctx, req.(*DeleteTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetTrialList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrialListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetTrialList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetTrialList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetTrialList(ctx, req.(*GetTrialListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetTrial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetTrial(ctx, req.(*GetTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateTrialStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrialStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateTrialStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/UpdateTrialStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateTrialStatus(ctx, req.(*UpdateTrialStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ReportObservationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportObservationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ReportObservationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/ReportObservationLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ReportObservationLog(ctx, req.(*ReportObservationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetObservationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetObservationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetObservationLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetObservationLog(ctx, req.(*GetObservationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetSuggestions(ctx, req.(*GetSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ValidateAlgorithmSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAlgorithmSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ValidateAlgorithmSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/ValidateAlgorithmSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ValidateAlgorithmSettings(ctx, req.(*ValidateAlgorithmSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterExperiment",
			Handler:    _Manager_RegisterExperiment_Handler,
		},
		{
			MethodName: "DeleteExperiment",
			Handler:    _Manager_DeleteExperiment_Handler,
		},
		{
			MethodName: "GetExperiment",
			Handler:    _Manager_GetExperiment_Handler,
		},
		{
			MethodName: "GetExperimentList",
			Handler:    _Manager_GetExperimentList_Handler,
		},
		{
			MethodName: "UpdateExperimentStatus",
			Handler:    _Manager_UpdateExperimentStatus_Handler,
		},
		{
			MethodName: "UpdateAlgorithmSpec",
			Handler:    _Manager_UpdateAlgorithmSpec_Handler,
		},
		{
			MethodName: "RegisterTrial",
			Handler:    _Manager_RegisterTrial_Handler,
		},
		{
			MethodName: "DeleteTrial",
			Handler:    _Manager_DeleteTrial_Handler,
		},
		{
			MethodName: "GetTrialList",
			Handler:    _Manager_GetTrialList_Handler,
		},
		{
			MethodName: "GetTrial",
			Handler:    _Manager_GetTrial_Handler,
		},
		{
			MethodName: "UpdateTrialStatus",
			Handler:    _Manager_UpdateTrialStatus_Handler,
		},
		{
			MethodName: "ReportObservationLog",
			Handler:    _Manager_ReportObservationLog_Handler,
		},
		{
			MethodName: "GetObservationLog",
			Handler:    _Manager_GetObservationLog_Handler,
		},
		{
			MethodName: "GetSuggestions",
			Handler:    _Manager_GetSuggestions_Handler,
		},
		{
			MethodName: "ValidateAlgorithmSettings",
			Handler:    _Manager_ValidateAlgorithmSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for Suggestion service

type SuggestionClient interface {
	GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error)
	ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error)
}

type suggestionClient struct {
	cc *grpc.ClientConn
}

func NewSuggestionClient(cc *grpc.ClientConn) SuggestionClient {
	return &suggestionClient{cc}
}

func (c *suggestionClient) GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error) {
	out := new(GetSuggestionsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Suggestion/GetSuggestions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suggestionClient) ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error) {
	out := new(ValidateAlgorithmSettingsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Suggestion/ValidateAlgorithmSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Suggestion service

type SuggestionServer interface {
	GetSuggestions(context.Context, *GetSuggestionsRequest) (*GetSuggestionsReply, error)
	ValidateAlgorithmSettings(context.Context, *ValidateAlgorithmSettingsRequest) (*ValidateAlgorithmSettingsReply, error)
}

func RegisterSuggestionServer(s *grpc.Server, srv SuggestionServer) {
	s.RegisterService(&_Suggestion_serviceDesc, srv)
}

func _Suggestion_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Suggestion/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServer).GetSuggestions(ctx, req.(*GetSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Suggestion_ValidateAlgorithmSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAlgorithmSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServer).ValidateAlgorithmSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Suggestion/ValidateAlgorithmSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServer).ValidateAlgorithmSettings(ctx, req.(*ValidateAlgorithmSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Suggestion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.Suggestion",
	HandlerType: (*SuggestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _Suggestion_GetSuggestions_Handler,
		},
		{
			MethodName: "ValidateAlgorithmSettings",
			Handler:    _Suggestion_ValidateAlgorithmSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for EarlyStopping service

type EarlyStoppingClient interface {
}

type earlyStoppingClient struct {
	cc *grpc.ClientConn
}

func NewEarlyStoppingClient(cc *grpc.ClientConn) EarlyStoppingClient {
	return &earlyStoppingClient{cc}
}

// Server API for EarlyStopping service

type EarlyStoppingServer interface {
}

func RegisterEarlyStoppingServer(s *grpc.Server, srv EarlyStoppingServer) {
	s.RegisterService(&_EarlyStopping_serviceDesc, srv)
}

var _EarlyStopping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.EarlyStopping",
	HandlerType: (*EarlyStoppingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0x5b, 0x73, 0xdb, 0xd6,
	0x11, 0x36, 0xa8, 0x9b, 0xb9, 0x34, 0x29, 0xea, 0x48, 0xb6, 0x29, 0xf8, 0x26, 0x23, 0xbe, 0x28,
	0x8a, 0x2d, 0xd9, 0x4c, 0x5a, 0x3b, 0xaa, 0x93, 0x54, 0xa1, 0x68, 0x8d, 0x62, 0x9a, 0xf2, 0x80,
	0x54, 0xd2, 0xa4, 0x9d, 0xb2, 0x10, 0x7d, 0x4c, 0xa3, 0x03, 0x02, 0x28, 0x00, 0xda, 0x56, 0x3c,
	0x9e, 0xe9, 0x78, 0xfa, 0xd0, 0x4e, 0xa7, 0x99, 0x7a, 0xfa, 0xd2, 0xcb, 0x1f, 0xc8, 0x4b, 0xfb,
	0xd4, 0x69, 0x7f, 0x40, 0x5f, 0xfb, 0xd6, 0x69, 0x7f, 0x41, 0xfb, 0x0f, 0xfa, 0xda, 0x99, 0xce,
	0x59, 0xdc, 0x0e, 0x80, 0x03, 0x89, 0x72, 0xda, 0xc9, 0x1b, 0xb0, 0xe7, 0x3b, 0xbb, 0xdf, 0xee,
	0xd9, 0xdd, 0xb3, 0x04, 0xa1, 0xa8, 0xd9, 0xfa, 0xaa, 0xed, 0x58, 0x9e, 0x45, 0xca, 0xec, 0xf1,
	0xc9, 0xcd, 0x55, 0xcd, 0xb0, 0x1f, 0x6b, 0x75, 0xf9, 0xec, 0xc0, 0xb2, 0x06, 0x06, 0x5d, 0xd3,
	0x6c, 0x7d, 0x4d, 0x33, 0x4d, 0xcb, 0xd3, 0x3c, 0xdd, 0x32, 0x5d, 0x1f, 0xac, 0x7c, 0x17, 0xca,
	0x77, 0xa9, 0xe6, 0xea, 0x7b, 0x06, 0xed, 0xd8, 0x5a, 0x9f, 0x92, 0x2a, 0x4c, 0x0c, 0xb5, 0x67,
	0x35, 0x69, 0x49, 0x5a, 0x2e, 0xaa, 0xec, 0x11, 0x25, 0xba, 0x59, 0x2b, 0x04, 0x12, 0xdd, 0x24,
	0x04, 0x26, 0x0d, 0xdd, 0xf5, 0x6a, 0x13, 0x4b, 0x13, 0xcb, 0x45, 0x15, 0x9f, 0x99, 0xcc, 0xf5,
	0xa8, 0x5d, 0x9b, 0x44, 0x18, 0x3e, 0x2b, 0xbf, 0x97, 0xa0, 0xfc, 0x40, 0x73, 0xb4, 0x21, 0xf5,
	0xa8, 0xd3, 0xb1, 0x69, 0x9f, 0xa1, 0x4c, 0x6d, 0x48, 0x03, 0xf5, 0xf8, 0x4c, 0x1a, 0x50, 0xb1,
	0x43, 0x50, 0xcf, 0xdb, 0xb7, 0x29, 0x9a, 0xaa, 0xd4, 0xcf, 0xae, 0x26, 0x1c, 0x59, 0x8d, 0x34,
	0x75, 0xf7, 0x6d, 0xaa, 0x96, 0x6d, 0xfe, 0x95, 0x29, 0x79, 0x14, 0xf8, 0xd1, 0x73, 0x99, 0x23,
	0xb5, 0x89, 0x25, 0x69, 0xb9, 0x94, 0x51, 0x92, 0x70, 0x56, 0x2d, 0x3f, 0xe2, 0x5f, 0x95, 0xbf,
	0x48, 0x50, 0xde, 0xd9, 0xfb, 0x21, 0xed, 0x7b, 0xfa, 0x13, 0x8a, 0x7c, 0x6f, 0xc0, 0x24, 0x32,
	0x92, 0x84, 0x8c, 0x22, 0x2c, 0x32, 0x42, 0x24, 0xf3, 0x70, 0x60, 0x69, 0x06, 0xfa, 0x50, 0x50,
	0xf1, 0x99, 0xd4, 0xe1, 0xa4, 0x15, 0x42, 0x7b, 0x43, 0xea, 0x39, 0x7a, 0xbf, 0x87, 0x61, 0x98,
	0xc0, 0x30, 0xcc, 0x47, 0x8b, 0xf7, 0x71, 0xad, 0xcd, 0xa2, 0x72, 0x1b, 0x6a, 0xda, 0xc3, 0x87,
	0x3a, 0x3b, 0x2b, 0xcd, 0x08, 0x36, 0xb9, 0xb8, 0xcb, 0xad, 0x4d, 0x62, 0xdc, 0x4f, 0xc5, 0xeb,
	0xfe, 0x3e, 0x97, 0x6d, 0x74, 0x95, 0x3b, 0x50, 0xdd, 0x30, 0x06, 0x96, 0xa3, 0x7b, 0x8f, 0x87,
	0x1d, 0xea, 0x79, 0xba, 0x39, 0x10, 0xc6, 0x7d, 0x01, 0xa6, 0x9e, 0x68, 0xc6, 0x88, 0x06, 0x27,
	0xeb, 0xbf, 0x28, 0xf3, 0x30, 0xd7, 0xd4, 0x1c, 0x63, 0xbf, 0xe3, 0x59, 0xb6, 0xad, 0x9b, 0x03,
	0x16, 0x06, 0xe5, 0x1f, 0x12, 0x94, 0x63, 0x9d, 0x2c, 0x30, 0x97, 0xa1, 0xa2, 0x85, 0x82, 0x1e,
	0xa7, 0xba, 0x1c, 0x49, 0xd1, 0x8b, 0x16, 0xcc, 0xc5, 0x30, 0xd7, 0x27, 0x53, 0x2b, 0x2c, 0x4d,
	0x2c, 0x97, 0xea, 0x17, 0x52, 0xc1, 0x4c, 0x73, 0x56, 0xab, 0x5a, 0xda, 0x8b, 0x07, 0x30, 0x4f,
	0x19, 0xb7, 0x9e, 0x1b, 0x90, 0xeb, 0xb9, 0x36, 0xed, 0x07, 0x27, 0xbd, 0x94, 0xd2, 0x97, 0xf1,
	0x42, 0x9d, 0xa3, 0x19, 0xc7, 0xfe, 0x2e, 0x41, 0xb1, 0xad, 0xb9, 0x0d, 0xcb, 0x7c, 0xa4, 0x0f,
	0xc8, 0x7b, 0x70, 0x62, 0xe0, 0x68, 0xf6, 0xe3, 0x5e, 0x1f, 0xdf, 0xd1, 0xa5, 0x52, 0x5d, 0x4e,
	0x29, 0xde, 0x62, 0x10, 0x7f, 0x87, 0x5a, 0x1a, 0xc4, 0x2f, 0xa4, 0x01, 0x60, 0xd9, 0xd4, 0xf1,
	0xeb, 0x0b, 0xa3, 0x5a, 0xaa, 0xbf, 0x91, 0xda, 0x1c, 0x19, 0x5b, 0xdd, 0x89, 0xa0, 0x2a, 0xb7,
	0x4d, 0xde, 0x04, 0x88, 0x57, 0xc8, 0x37, 0xa1, 0x18, 0xad, 0xd5, 0x24, 0x8c, 0x5b, 0x2d, 0x9d,
	0x84, 0xe1, 0xba, 0x1a, 0x43, 0x15, 0x03, 0x4a, 0x1c, 0x4d, 0x72, 0x0e, 0xc0, 0x1c, 0x0d, 0x7b,
	0x86, 0xb6, 0x4f, 0x1d, 0x17, 0xdd, 0x9a, 0x52, 0x8b, 0xe6, 0x68, 0xd8, 0x42, 0x01, 0x5b, 0xd6,
	0x4d, 0x7b, 0xe4, 0xf5, 0x5c, 0xfd, 0x73, 0x8a, 0xc7, 0x33, 0xa5, 0x16, 0x51, 0xd2, 0xd1, 0x3f,
	0xa7, 0xe4, 0x02, 0x94, 0xac, 0x91, 0x17, 0xad, 0x4f, 0xe0, 0x3a, 0xf8, 0x22, 0x06, 0x50, 0xfe,
	0x2d, 0x41, 0x31, 0xa2, 0xc1, 0x52, 0x23, 0x22, 0xd2, 0x8b, 0xaa, 0xa7, 0xa8, 0x96, 0x23, 0x29,
	0x56, 0xec, 0x1e, 0x9c, 0x8c, 0xcb, 0x5e, 0x73, 0x5d, 0x7d, 0x60, 0x0e, 0xa9, 0xe9, 0x85, 0x81,
	0xbb, 0x9e, 0xe7, 0x66, 0xdc, 0x07, 0x36, 0xe2, 0x4d, 0xea, 0x82, 0x2d, 0x90, 0xca, 0xdf, 0x83,
	0x05, 0x11, 0x9a, 0x6c, 0x42, 0x89, 0xb7, 0xe8, 0x07, 0x56, 0xc9, 0xeb, 0x37, 0xf1, 0x4e, 0x95,
	0xdf, 0xa6, 0xfc, 0xa7, 0x00, 0x95, 0xe6, 0x33, 0x9b, 0x3a, 0x3a, 0x7b, 0xc7, 0xb2, 0xb8, 0x03,
	0x10, 0x11, 0x09, 0xf5, 0xe6, 0xf6, 0x31, 0x4c, 0x4a, 0x0e, 0x4f, 0xd6, 0xa1, 0x18, 0xb5, 0x82,
	0x20, 0x0c, 0xb9, 0x2d, 0x07, 0x37, 0xc7, 0x70, 0xb6, 0x37, 0xaa, 0x97, 0x9c, 0xde, 0x97, 0xa8,
	0x60, 0x35, 0x86, 0xb3, 0x13, 0xf3, 0x1c, 0x5d, 0x33, 0x7a, 0x1e, 0x1d, 0xda, 0x86, 0xe6, 0xd1,
	0xa0, 0x8b, 0x97, 0x51, 0xda, 0x0d, 0x84, 0xe4, 0x06, 0x60, 0x94, 0x0d, 0x83, 0x1a, 0x3d, 0x1f,
	0xdf, 0xb7, 0x46, 0xa6, 0x57, 0x9b, 0xc2, 0x7c, 0x22, 0xe1, 0x5a, 0x97, 0x2d, 0x35, 0xd8, 0x0a,
	0xb9, 0x02, 0xb3, 0x43, 0xed, 0x59, 0x02, 0x3c, 0x8d, 0xe0, 0xf2, 0x50, 0x7b, 0xc6, 0xe1, 0xde,
	0x81, 0x53, 0x61, 0x87, 0xeb, 0x5b, 0x86, 0x41, 0xfb, 0x9e, 0x15, 0x5c, 0x05, 0x33, 0x48, 0x64,
	0x21, 0x58, 0x6d, 0x84, 0x8b, 0x2c, 0x83, 0x94, 0x57, 0x05, 0xa8, 0x72, 0xf1, 0xf7, 0x34, 0x6f,
	0x84, 0xb9, 0xec, 0x7a, 0x9a, 0xe3, 0xf5, 0x3c, 0x3d, 0x6a, 0x4a, 0x45, 0x94, 0x74, 0xf5, 0x21,
	0x25, 0x57, 0x61, 0xb6, 0x6f, 0x0d, 0x6d, 0x83, 0xfa, 0xd9, 0xc9, 0x30, 0x7e, 0xfb, 0xab, 0xc4,
	0x62, 0x04, 0xee, 0x42, 0xb1, 0x6f, 0x99, 0x7e, 0x83, 0xc5, 0x78, 0x56, 0xea, 0xb7, 0xd2, 0x1d,
	0x26, 0x65, 0x9b, 0x13, 0x34, 0xc2, 0xad, 0x78, 0x33, 0xc4, 0x9a, 0x94, 0xef, 0xc3, 0xe9, 0x1c,
	0x14, 0x29, 0xc1, 0x4c, 0x43, 0x6d, 0x6e, 0x74, 0x9b, 0x9b, 0xd5, 0x63, 0xec, 0x45, 0xdd, 0x6d,
	0xb7, 0xb7, 0xdb, 0x5b, 0x55, 0x89, 0x54, 0x00, 0xd4, 0x66, 0xa7, 0xbb, 0xa1, 0x76, 0xd9, 0x7b,
	0x81, 0x94, 0xa1, 0xd8, 0xd9, 0x6d, 0x34, 0x9a, 0xcd, 0xcd, 0xe6, 0x66, 0x75, 0x82, 0x00, 0x4c,
	0xdf, 0xdd, 0xd8, 0x6e, 0x35, 0x37, 0xab, 0x93, 0xca, 0x9f, 0x24, 0x80, 0xd8, 0x80, 0xb0, 0xef,
	0xdf, 0x85, 0x59, 0x1a, 0x21, 0xfc, 0x0e, 0xea, 0xe7, 0xda, 0xb9, 0x7c, 0xff, 0x58, 0xc2, 0x54,
	0x68, 0x32, 0xd7, 0x5b, 0x30, 0xc7, 0xeb, 0xc1, 0x10, 0x04, 0x99, 0x77, 0xe1, 0x90, 0x48, 0xa9,
	0x55, 0x9a, 0x92, 0x28, 0x1f, 0xc0, 0xbc, 0xa0, 0xe0, 0x8e, 0x70, 0x71, 0xd5, 0x61, 0xda, 0xbf,
	0x06, 0x8f, 0xb0, 0xe7, 0x53, 0x28, 0xfa, 0x7b, 0x5a, 0x16, 0x36, 0x49, 0x96, 0x0f, 0xcc, 0x93,
	0xa1, 0x1d, 0x66, 0x0e, 0x93, 0x74, 0x98, 0x80, 0x5c, 0x87, 0x69, 0x3f, 0x0b, 0x83, 0x68, 0x9d,
	0x4c, 0xf9, 0xe8, 0x2b, 0x52, 0x03, 0x90, 0xf2, 0x3e, 0x94, 0x76, 0xf6, 0x5c, 0xea, 0x3c, 0xf1,
	0x9b, 0xe2, 0x1a, 0xcc, 0x04, 0x39, 0x1c, 0x74, 0x85, 0x9c, 0xed, 0x21, 0x4a, 0xf9, 0x08, 0x2a,
	0xdc, 0x7e, 0xc6, 0xef, 0x36, 0x80, 0xbf, 0x68, 0x58, 0x03, 0x37, 0xe7, 0x32, 0x88, 0xbc, 0x51,
	0x39, 0xac, 0xf2, 0xa5, 0x04, 0x45, 0xac, 0x36, 0x3c, 0xb7, 0xab, 0x89, 0xf3, 0xe7, 0x22, 0xc5,
	0x1d, 0x30, 0x5e, 0xde, 0x9f, 0xe4, 0x77, 0xe8, 0x71, 0xfb, 0xa5, 0xb0, 0x2d, 0x93, 0x45, 0x38,
	0xee, 0x8c, 0xcc, 0xf8, 0xf2, 0x2e, 0xaa, 0x33, 0xce, 0xc8, 0xc4, 0x0b, 0xf9, 0xcf, 0x05, 0x28,
	0xf9, 0x54, 0xff, 0xb7, 0xe5, 0x7c, 0x2f, 0x5b, 0xce, 0xe9, 0x1b, 0x86, 0x33, 0xbb, 0x1a, 0xf4,
	0x26, 0x71, 0x11, 0x93, 0x3b, 0x50, 0xb2, 0xe2, 0xb3, 0xc1, 0x66, 0x99, 0x1d, 0x13, 0xb8, 0xd3,
	0x53, 0x79, 0xb8, 0xb2, 0x0b, 0x24, 0xab, 0x9e, 0x15, 0xfc, 0x83, 0x66, 0x7b, 0x93, 0x15, 0x78,
	0xaa, 0xfa, 0xcb, 0x50, 0x6c, 0xec, 0xdc, 0x7f, 0xd0, 0x6a, 0xb2, 0xce, 0x50, 0x60, 0xd5, 0x7e,
	0x6f, 0xbb, 0xd5, 0xca, 0x54, 0xfe, 0x0b, 0x98, 0x42, 0xb5, 0xc2, 0xf4, 0xbf, 0x06, 0x93, 0x5c,
	0xa1, 0xd7, 0x84, 0x9e, 0xb3, 0x1a, 0x47, 0x14, 0xa9, 0xc3, 0x74, 0xa2, 0x9c, 0xe5, 0xfc, 0x48,
	0xa9, 0x01, 0x52, 0xf9, 0x18, 0x16, 0x55, 0x3a, 0xd0, 0x5d, 0x8f, 0x3a, 0x71, 0xb5, 0xab, 0xf4,
	0x47, 0x23, 0xea, 0x7a, 0xe4, 0x5d, 0x80, 0x38, 0xb7, 0x82, 0xb1, 0x6a, 0x31, 0xb7, 0x47, 0xa8,
	0x1c, 0x58, 0x59, 0x84, 0xd3, 0x22, 0xbd, 0xb6, 0xb1, 0xaf, 0x7c, 0x08, 0xa7, 0x37, 0xa9, 0x41,
	0x3d, 0x9a, 0x35, 0x38, 0x6e, 0x8e, 0x2b, 0xa7, 0xe1, 0x64, 0x56, 0x07, 0x53, 0xfe, 0x01, 0x2c,
	0x6c, 0x51, 0xef, 0x2b, 0x68, 0xde, 0x01, 0x92, 0x52, 0x60, 0x1b, 0xfb, 0x5f, 0x25, 0x12, 0x23,
	0x98, 0xe3, 0xfa, 0xe8, 0x68, 0x38, 0xd4, 0x9c, 0xfd, 0xf1, 0x8b, 0xf9, 0x56, 0x74, 0xa6, 0x85,
	0xf1, 0x5a, 0x74, 0x78, 0xb0, 0x32, 0xd4, 0x12, 0x7e, 0xb4, 0x74, 0x37, 0x0c, 0x86, 0x32, 0x84,
	0x53, 0x82, 0x35, 0xe6, 0x67, 0x07, 0x16, 0xf8, 0xcb, 0x01, 0xd9, 0xea, 0x34, 0x6c, 0x5b, 0x4b,
	0xf9, 0xc6, 0x7d, 0xbf, 0xd4, 0x79, 0x9a, 0x12, 0xe9, 0xd4, 0x55, 0x7e, 0x2a, 0xc1, 0xb9, 0x5d,
	0xfb, 0xa1, 0xc6, 0x9f, 0x56, 0xc0, 0xf6, 0x88, 0xa7, 0x43, 0xde, 0x07, 0x30, 0xe9, 0xd3, 0xde,
	0xd1, 0x42, 0x52, 0x34, 0xe9, 0xd3, 0xe0, 0xba, 0x3a, 0x07, 0x67, 0xf2, 0x98, 0xb0, 0xec, 0x79,
	0x25, 0x81, 0xec, 0xaf, 0x27, 0x87, 0xae, 0xa3, 0xd2, 0xfc, 0x08, 0x08, 0xa3, 0xc9, 0xfd, 0x86,
	0x8a, 0xab, 0xf8, 0xe0, 0xf1, 0xae, 0x6a, 0xd2, 0xa7, 0x09, 0x09, 0x3b, 0x48, 0x21, 0x25, 0xbf,
	0x94, 0x16, 0xc2, 0x2a, 0xc3, 0xe2, 0x0e, 0x89, 0xae, 0xc0, 0x14, 0x0e, 0x6f, 0x41, 0xa6, 0x2e,
	0x88, 0x1a, 0x81, 0xea, 0x43, 0x94, 0x05, 0x20, 0x29, 0x1d, 0x4c, 0xf3, 0xdb, 0x40, 0xfc, 0x02,
	0x4b, 0xe8, 0x65, 0x77, 0x2d, 0x0e, 0x85, 0x9c, 0xef, 0x45, 0x94, 0x60, 0xed, 0x10, 0xa8, 0x26,
	0x36, 0x31, 0x45, 0xbf, 0x94, 0x60, 0x7e, 0x8b, 0x7a, 0x28, 0xe1, 0x72, 0x70, 0xfc, 0x58, 0x26,
	0xaf, 0x92, 0x42, 0xfa, 0x2a, 0x59, 0x84, 0xe3, 0xd4, 0x7c, 0xe8, 0x2f, 0x06, 0x97, 0x12, 0x35,
	0x1f, 0xe2, 0xd2, 0x29, 0x98, 0x7e, 0xa4, 0x1b, 0x1e, 0x75, 0x82, 0xb9, 0x38, 0x78, 0x53, 0x36,
	0x60, 0x2e, 0xc9, 0x88, 0x65, 0xfe, 0x35, 0x98, 0x46, 0x47, 0xc2, 0x5c, 0x17, 0xc7, 0x2c, 0xc0,
	0x28, 0x37, 0x60, 0x36, 0x54, 0x31, 0x66, 0x6c, 0xbe, 0x05, 0xe5, 0x78, 0x07, 0x33, 0x78, 0x94,
	0x33, 0xf2, 0xc2, 0x1c, 0xe0, 0x5b, 0xf8, 0x58, 0x76, 0x59, 0xe7, 0xca, 0x54, 0xcc, 0x41, 0x17,
	0x03, 0x57, 0x2c, 0x35, 0x38, 0x25, 0xb0, 0xca, 0x0e, 0xf5, 0x27, 0x12, 0x9c, 0x51, 0xa9, 0x6d,
	0x39, 0x5e, 0x72, 0xd8, 0x19, 0x93, 0xd3, 0x5d, 0x98, 0xe5, 0x6e, 0xd6, 0x9e, 0x61, 0x0d, 0x72,
	0x46, 0xd9, 0x94, 0xf6, 0x8a, 0x95, 0x78, 0x57, 0xce, 0xb0, 0xcb, 0x4b, 0xc4, 0x82, 0x71, 0x7c,
	0x17, 0x1b, 0xe0, 0xeb, 0xf0, 0x53, 0x7e, 0x80, 0xfd, 0x51, 0xa0, 0x54, 0xc4, 0x5c, 0x7a, 0x1d,
	0xe6, 0x5f, 0x48, 0x70, 0x72, 0x8b, 0x7a, 0x9d, 0xd1, 0x60, 0x40, 0x5d, 0xff, 0x6b, 0xc2, 0x51,
	0xeb, 0x22, 0xfb, 0x29, 0xa7, 0x20, 0xfa, 0x94, 0x73, 0x19, 0x2a, 0x8e, 0xaf, 0xba, 0x67, 0x8e,
	0x86, 0x7b, 0xd4, 0xc1, 0x2a, 0x99, 0x52, 0xcb, 0x81, 0xb4, 0x8d, 0x42, 0xa5, 0x81, 0x55, 0x9a,
	0xe0, 0x73, 0xf4, 0xaa, 0x78, 0x25, 0xc1, 0xd2, 0xc7, 0x9a, 0xa1, 0x27, 0xbb, 0x95, 0xff, 0x15,
	0x28, 0x72, 0x50, 0xf0, 0x3b, 0x46, 0x7a, 0x9d, 0xdf, 0x31, 0xe3, 0xf9, 0xaf, 0x2c, 0xc1, 0xf9,
	0x03, 0x28, 0xd9, 0xc6, 0xfe, 0xca, 0x2e, 0xf7, 0xb5, 0x13, 0x67, 0xba, 0x2a, 0x9c, 0xd8, 0x6d,
	0xdf, 0x6b, 0xef, 0x7c, 0xd2, 0xee, 0x75, 0x3f, 0x7d, 0xd0, 0xac, 0x1e, 0x63, 0x03, 0xdb, 0xe6,
	0xce, 0xee, 0x87, 0xad, 0x66, 0x55, 0x22, 0x33, 0x30, 0xb1, 0xdd, 0xee, 0x56, 0x0b, 0xe4, 0x04,
	0x1c, 0xdf, 0xdc, 0xee, 0x34, 0xd4, 0x66, 0xb7, 0x59, 0x9d, 0x20, 0xb3, 0x50, 0x6a, 0x6c, 0x74,
	0x9b, 0x5b, 0x3b, 0xea, 0x76, 0x63, 0xa3, 0x55, 0x9d, 0x5c, 0xb9, 0xcd, 0x7d, 0x94, 0x0c, 0x47,
	0xc5, 0x40, 0x6d, 0xf5, 0x18, 0xdb, 0x7c, 0x7f, 0xbb, 0xbd, 0x7d, 0x7f, 0xfb, 0x33, 0xa6, 0x93,
	0xbd, 0x6d, 0x7c, 0xc7, 0x7f, 0x2b, 0xd4, 0xff, 0x3a, 0x07, 0x33, 0xf7, 0x35, 0x53, 0x1b, 0x50,
	0x87, 0xfc, 0x4e, 0x8a, 0xdb, 0x33, 0xf7, 0x03, 0x71, 0x39, 0x15, 0xab, 0xdc, 0x19, 0x4e, 0xbe,
	0x32, 0x06, 0x12, 0x1b, 0xfe, 0xcb, 0xbf, 0xfd, 0xf3, 0x57, 0x85, 0xeb, 0xca, 0x05, 0xfc, 0xe2,
	0x1c, 0x98, 0x5f, 0xcb, 0xa2, 0xd7, 0xb9, 0xd9, 0x86, 0xfc, 0x46, 0x0a, 0x3b, 0x3e, 0xc7, 0x2d,
	0x6d, 0x31, 0x67, 0xd8, 0x93, 0x2f, 0x1d, 0x8a, 0x63, 0xbc, 0x6e, 0x21, 0xaf, 0x9b, 0x64, 0x2d,
	0xc1, 0x2b, 0x8d, 0x5d, 0x7b, 0x9e, 0x2a, 0x9a, 0x17, 0xe4, 0x17, 0x12, 0x76, 0x5c, 0x8e, 0x58,
	0xfa, 0xa3, 0x9e, 0x68, 0x50, 0x94, 0x2f, 0x1e, 0x0c, 0x62, 0x94, 0xde, 0x41, 0x4a, 0xab, 0xe4,
	0x5a, 0x82, 0x52, 0x02, 0x28, 0xe0, 0xf3, 0x73, 0x09, 0xaf, 0x9d, 0xe4, 0xd4, 0x45, 0xae, 0x1e,
	0x64, 0x8e, 0xbb, 0x2f, 0xe5, 0xcb, 0x87, 0x03, 0x19, 0xb7, 0x2b, 0xc8, 0x6d, 0x89, 0x9c, 0xcf,
	0xe7, 0x86, 0x76, 0xff, 0x28, 0x85, 0xcd, 0x3d, 0xf3, 0x29, 0xe6, 0x5a, 0xca, 0xd2, 0x81, 0xa3,
	0x9b, 0xbc, 0x32, 0x26, 0x9a, 0x91, 0xfb, 0x36, 0x92, 0x5b, 0x97, 0xbf, 0x91, 0x20, 0x27, 0xde,
	0x91, 0x8d, 0xe0, 0xba, 0xb4, 0x42, 0xbe, 0x94, 0x60, 0x5e, 0x30, 0x0d, 0x91, 0x37, 0x85, 0x2c,
	0x44, 0x43, 0x9c, 0x7c, 0x75, 0x1c, 0x28, 0x63, 0xfb, 0x1e, 0xb2, 0xbd, 0x25, 0xd7, 0x05, 0x6c,
	0x13, 0x70, 0x31, 0xd5, 0x97, 0x12, 0x94, 0x13, 0x83, 0x55, 0x26, 0xff, 0x44, 0xa3, 0x5b, 0x26,
	0xff, 0x04, 0xb3, 0xd9, 0x9b, 0x48, 0xec, 0x0d, 0x45, 0x16, 0x96, 0x2a, 0x02, 0xd7, 0xfd, 0xc1,
	0x81, 0xfc, 0x58, 0x82, 0x12, 0x37, 0x92, 0x91, 0x8b, 0xc2, 0x9a, 0x4b, 0x10, 0xb8, 0x70, 0x10,
	0x84, 0x99, 0xbf, 0x8e, 0xe6, 0xaf, 0x92, 0xcb, 0x82, 0x8a, 0x44, 0xd8, 0xda, 0xf3, 0xf8, 0x72,
	0x7d, 0x41, 0x7e, 0x26, 0xc1, 0x09, 0x7e, 0xdc, 0x22, 0x4a, 0x36, 0x93, 0xd3, 0xd3, 0xa1, 0xbc,
	0x74, 0x20, 0x86, 0xeb, 0x57, 0xe4, 0xad, 0x74, 0xa2, 0x47, 0x38, 0x41, 0x0d, 0x7a, 0x70, 0x3c,
	0x44, 0x90, 0xf3, 0x39, 0x26, 0x42, 0x0a, 0x67, 0x73, 0xd7, 0x99, 0xf9, 0x15, 0x34, 0x7f, 0x89,
	0x28, 0x42, 0xf3, 0xc9, 0x08, 0x7c, 0x21, 0xc1, 0x5c, 0x66, 0x90, 0x22, 0xe2, 0x3c, 0xcc, 0x0e,
	0x78, 0x99, 0xca, 0xcf, 0x99, 0xc9, 0x82, 0xac, 0x90, 0xcf, 0x0b, 0xd2, 0x95, 0x03, 0xb3, 0xd4,
	0xfc, 0xad, 0xc4, 0x7e, 0x37, 0x64, 0x07, 0x27, 0xb2, 0x92, 0x49, 0xbe, 0xdc, 0x19, 0x4f, 0x5e,
	0x1e, 0x0b, 0xcb, 0x98, 0x5d, 0x43, 0x66, 0x57, 0x94, 0x8b, 0xa9, 0x7c, 0xcd, 0xe2, 0x19, 0xb9,
	0x5f, 0xfb, 0x7d, 0x32, 0xc5, 0x4c, 0xd0, 0x27, 0xc5, 0xb4, 0x2e, 0x1f, 0x0e, 0x3c, 0x30, 0x7d,
	0x92, 0xe0, 0xe4, 0x41, 0xbe, 0x94, 0xa0, 0x92, 0x9c, 0x92, 0xc8, 0xa5, 0xac, 0xb9, 0xec, 0x50,
	0x27, 0x2b, 0x87, 0xa0, 0xb8, 0xce, 0xad, 0x9c, 0x49, 0x33, 0xe2, 0x90, 0x2c, 0x3e, 0x7f, 0x90,
	0x60, 0x31, 0x77, 0xa2, 0x21, 0x6b, 0x29, 0x4b, 0x87, 0x8d, 0x63, 0xf2, 0xf5, 0xf1, 0x37, 0x30,
	0x96, 0x37, 0x91, 0xe5, 0x5b, 0xca, 0x95, 0x04, 0xcb, 0xdc, 0x4d, 0xeb, 0xd2, 0x4a, 0xfd, 0x5f,
	0x12, 0x40, 0xec, 0x03, 0xf9, 0xec, 0xff, 0x17, 0x43, 0xf2, 0xfc, 0x6b, 0x0c, 0x4d, 0x7d, 0x16,
	0xca, 0x89, 0x3f, 0x2f, 0xf7, 0xa6, 0xf1, 0xbf, 0xfa, 0xb7, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x1e, 0xbd, 0xe4, 0x55, 0xe5, 0x1f, 0x00, 0x00,
}
