// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api_v1_alpha2 is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GetSuggestionsRequest
	GetSuggestionsReply
	ValidateAlgorithmSettingsRequest
	ValidateAlgorithmSettingsReply
*/
package api_v1_alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import dbif_v1_alpha2 "github.com/kubeflow/katib/pkg/api/v1alpha2/dbif"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Types of value for HyperParameter.
type ParameterType int32

const (
	ParameterType_UNKNOWN_TYPE ParameterType = 0
	ParameterType_DOUBLE       ParameterType = 1
	ParameterType_INT          ParameterType = 2
	ParameterType_DISCRETE     ParameterType = 3
	ParameterType_CATEGORICAL  ParameterType = 4
)

var ParameterType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "DOUBLE",
	2: "INT",
	3: "DISCRETE",
	4: "CATEGORICAL",
}
var ParameterType_value = map[string]int32{
	"UNKNOWN_TYPE": 0,
	"DOUBLE":       1,
	"INT":          2,
	"DISCRETE":     3,
	"CATEGORICAL":  4,
}

func (x ParameterType) String() string {
	return proto.EnumName(ParameterType_name, int32(x))
}
func (ParameterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Direction of optimization. Minimize or Maximize.
type ObjectiveType int32

const (
	ObjectiveType_UNKNOWN  ObjectiveType = 0
	ObjectiveType_MINIMIZE ObjectiveType = 1
	ObjectiveType_MAXIMIZE ObjectiveType = 2
)

var ObjectiveType_name = map[int32]string{
	0: "UNKNOWN",
	1: "MINIMIZE",
	2: "MAXIMIZE",
}
var ObjectiveType_value = map[string]int32{
	"UNKNOWN":  0,
	"MINIMIZE": 1,
	"MAXIMIZE": 2,
}

func (x ObjectiveType) String() string {
	return proto.EnumName(ObjectiveType_name, int32(x))
}
func (ObjectiveType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ExperimentStatus_ExperimentConditionType int32

const (
	ExperimentStatus_CREATED    ExperimentStatus_ExperimentConditionType = 0
	ExperimentStatus_RUNNING    ExperimentStatus_ExperimentConditionType = 1
	ExperimentStatus_RESTARTING ExperimentStatus_ExperimentConditionType = 2
	ExperimentStatus_SUCCEEDED  ExperimentStatus_ExperimentConditionType = 3
	ExperimentStatus_FAILED     ExperimentStatus_ExperimentConditionType = 4
	ExperimentStatus_UNKNOWN    ExperimentStatus_ExperimentConditionType = 5
)

var ExperimentStatus_ExperimentConditionType_name = map[int32]string{
	0: "CREATED",
	1: "RUNNING",
	2: "RESTARTING",
	3: "SUCCEEDED",
	4: "FAILED",
	5: "UNKNOWN",
}
var ExperimentStatus_ExperimentConditionType_value = map[string]int32{
	"CREATED":    0,
	"RUNNING":    1,
	"RESTARTING": 2,
	"SUCCEEDED":  3,
	"FAILED":     4,
	"UNKNOWN":    5,
}

func (x ExperimentStatus_ExperimentConditionType) String() string {
	return proto.EnumName(ExperimentStatus_ExperimentConditionType_name, int32(x))
}
func (ExperimentStatus_ExperimentConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type TrialStatus_TrialConditionType int32

const (
	TrialStatus_CREATED   TrialStatus_TrialConditionType = 0
	TrialStatus_RUNNING   TrialStatus_TrialConditionType = 1
	TrialStatus_SUCCEEDED TrialStatus_TrialConditionType = 2
	TrialStatus_KILLED    TrialStatus_TrialConditionType = 3
	TrialStatus_FAILED    TrialStatus_TrialConditionType = 4
	TrialStatus_UNKNOWN   TrialStatus_TrialConditionType = 5
)

var TrialStatus_TrialConditionType_name = map[int32]string{
	0: "CREATED",
	1: "RUNNING",
	2: "SUCCEEDED",
	3: "KILLED",
	4: "FAILED",
	5: "UNKNOWN",
}
var TrialStatus_TrialConditionType_value = map[string]int32{
	"CREATED":   0,
	"RUNNING":   1,
	"SUCCEEDED": 2,
	"KILLED":    3,
	"FAILED":    4,
	"UNKNOWN":   5,
}

func (x TrialStatus_TrialConditionType) String() string {
	return proto.EnumName(TrialStatus_TrialConditionType_name, int32(x))
}
func (TrialStatus_TrialConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18, 0}
}

// *
// Feasible space for optimization.
// Int and Double type use Max/Min.
// Discrete and Categorical type use List.
type FeasibleSpace struct {
	Max  string   `protobuf:"bytes,1,opt,name=max" json:"max,omitempty"`
	Min  string   `protobuf:"bytes,2,opt,name=min" json:"min,omitempty"`
	List []string `protobuf:"bytes,3,rep,name=list" json:"list,omitempty"`
	Step string   `protobuf:"bytes,4,opt,name=step" json:"step,omitempty"`
}

func (m *FeasibleSpace) Reset()                    { *m = FeasibleSpace{} }
func (m *FeasibleSpace) String() string            { return proto.CompactTextString(m) }
func (*FeasibleSpace) ProtoMessage()               {}
func (*FeasibleSpace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FeasibleSpace) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *FeasibleSpace) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *FeasibleSpace) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *FeasibleSpace) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

// *
// Config for a Hyper parameter.
// Katib will create each Hyper parameter from this config.
type ParameterSpec struct {
	Name          string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ParameterType ParameterType  `protobuf:"varint,2,opt,name=parameter_type,json=parameterType,enum=api.v1.alpha2.ParameterType" json:"parameter_type,omitempty"`
	FeasibleSpace *FeasibleSpace `protobuf:"bytes,3,opt,name=feasible_space,json=feasibleSpace" json:"feasible_space,omitempty"`
}

func (m *ParameterSpec) Reset()                    { *m = ParameterSpec{} }
func (m *ParameterSpec) String() string            { return proto.CompactTextString(m) }
func (*ParameterSpec) ProtoMessage()               {}
func (*ParameterSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ParameterSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterSpec) GetParameterType() ParameterType {
	if m != nil {
		return m.ParameterType
	}
	return ParameterType_UNKNOWN_TYPE
}

func (m *ParameterSpec) GetFeasibleSpace() *FeasibleSpace {
	if m != nil {
		return m.FeasibleSpace
	}
	return nil
}

type ObjectiveSpec struct {
	Type                  ObjectiveType `protobuf:"varint,1,opt,name=type,enum=api.v1.alpha2.ObjectiveType" json:"type,omitempty"`
	Goal                  float32       `protobuf:"fixed32,2,opt,name=goal" json:"goal,omitempty"`
	ObjectiveMetricName   string        `protobuf:"bytes,3,opt,name=objective_metric_name,json=objectiveMetricName" json:"objective_metric_name,omitempty"`
	AdditionalMetricNames []string      `protobuf:"bytes,4,rep,name=additional_metric_names,json=additionalMetricNames" json:"additional_metric_names,omitempty"`
}

func (m *ObjectiveSpec) Reset()                    { *m = ObjectiveSpec{} }
func (m *ObjectiveSpec) String() string            { return proto.CompactTextString(m) }
func (*ObjectiveSpec) ProtoMessage()               {}
func (*ObjectiveSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ObjectiveSpec) GetType() ObjectiveType {
	if m != nil {
		return m.Type
	}
	return ObjectiveType_UNKNOWN
}

func (m *ObjectiveSpec) GetGoal() float32 {
	if m != nil {
		return m.Goal
	}
	return 0
}

func (m *ObjectiveSpec) GetObjectiveMetricName() string {
	if m != nil {
		return m.ObjectiveMetricName
	}
	return ""
}

func (m *ObjectiveSpec) GetAdditionalMetricNames() []string {
	if m != nil {
		return m.AdditionalMetricNames
	}
	return nil
}

type AlgorithmSetting struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *AlgorithmSetting) Reset()                    { *m = AlgorithmSetting{} }
func (m *AlgorithmSetting) String() string            { return proto.CompactTextString(m) }
func (*AlgorithmSetting) ProtoMessage()               {}
func (*AlgorithmSetting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlgorithmSetting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlgorithmSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EarlyStoppingSpec struct {
}

func (m *EarlyStoppingSpec) Reset()                    { *m = EarlyStoppingSpec{} }
func (m *EarlyStoppingSpec) String() string            { return proto.CompactTextString(m) }
func (*EarlyStoppingSpec) ProtoMessage()               {}
func (*EarlyStoppingSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AlgorithmSpec struct {
	AlgorithmName     string              `protobuf:"bytes,1,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
	AlgorithmSetting  []*AlgorithmSetting `protobuf:"bytes,2,rep,name=algorithm_setting,json=algorithmSetting" json:"algorithm_setting,omitempty"`
	EarlyStoppingSpec *EarlyStoppingSpec  `protobuf:"bytes,3,opt,name=early_stopping_spec,json=earlyStoppingSpec" json:"early_stopping_spec,omitempty"`
}

func (m *AlgorithmSpec) Reset()                    { *m = AlgorithmSpec{} }
func (m *AlgorithmSpec) String() string            { return proto.CompactTextString(m) }
func (*AlgorithmSpec) ProtoMessage()               {}
func (*AlgorithmSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AlgorithmSpec) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *AlgorithmSpec) GetAlgorithmSetting() []*AlgorithmSetting {
	if m != nil {
		return m.AlgorithmSetting
	}
	return nil
}

func (m *AlgorithmSpec) GetEarlyStoppingSpec() *EarlyStoppingSpec {
	if m != nil {
		return m.EarlyStoppingSpec
	}
	return nil
}

// *
// NasConfig contains a config of NAS job
type NasConfig struct {
	GraphConfig *GraphConfig          `protobuf:"bytes,1,opt,name=graph_config,json=graphConfig" json:"graph_config,omitempty"`
	Operations  *NasConfig_Operations `protobuf:"bytes,2,opt,name=operations" json:"operations,omitempty"`
}

func (m *NasConfig) Reset()                    { *m = NasConfig{} }
func (m *NasConfig) String() string            { return proto.CompactTextString(m) }
func (*NasConfig) ProtoMessage()               {}
func (*NasConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NasConfig) GetGraphConfig() *GraphConfig {
	if m != nil {
		return m.GraphConfig
	}
	return nil
}

func (m *NasConfig) GetOperations() *NasConfig_Operations {
	if m != nil {
		return m.Operations
	}
	return nil
}

type NasConfig_Operations struct {
	Operation []*Operation `protobuf:"bytes,1,rep,name=operation" json:"operation,omitempty"`
}

func (m *NasConfig_Operations) Reset()                    { *m = NasConfig_Operations{} }
func (m *NasConfig_Operations) String() string            { return proto.CompactTextString(m) }
func (*NasConfig_Operations) ProtoMessage()               {}
func (*NasConfig_Operations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *NasConfig_Operations) GetOperation() []*Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

// *
// GraphConfig contains a config of DAG
type GraphConfig struct {
	NumLayers   int32   `protobuf:"varint,1,opt,name=num_layers,json=numLayers" json:"num_layers,omitempty"`
	InputSizes  []int32 `protobuf:"varint,2,rep,packed,name=input_sizes,json=inputSizes" json:"input_sizes,omitempty"`
	OutputSizes []int32 `protobuf:"varint,3,rep,packed,name=output_sizes,json=outputSizes" json:"output_sizes,omitempty"`
}

func (m *GraphConfig) Reset()                    { *m = GraphConfig{} }
func (m *GraphConfig) String() string            { return proto.CompactTextString(m) }
func (*GraphConfig) ProtoMessage()               {}
func (*GraphConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GraphConfig) GetNumLayers() int32 {
	if m != nil {
		return m.NumLayers
	}
	return 0
}

func (m *GraphConfig) GetInputSizes() []int32 {
	if m != nil {
		return m.InputSizes
	}
	return nil
}

func (m *GraphConfig) GetOutputSizes() []int32 {
	if m != nil {
		return m.OutputSizes
	}
	return nil
}

// *
// Config for operations in DAG
type Operation struct {
	OperationType  string                    `protobuf:"bytes,1,opt,name=operation_type,json=operationType" json:"operation_type,omitempty"`
	ParameterSpecs *Operation_ParameterSpecs `protobuf:"bytes,2,opt,name=parameter_specs,json=parameterSpecs" json:"parameter_specs,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Operation) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *Operation) GetParameterSpecs() *Operation_ParameterSpecs {
	if m != nil {
		return m.ParameterSpecs
	}
	return nil
}

// *
// List of ParameterSpec
type Operation_ParameterSpecs struct {
	Parameters []*ParameterSpec `protobuf:"bytes,1,rep,name=parameters" json:"parameters,omitempty"`
}

func (m *Operation_ParameterSpecs) Reset()                    { *m = Operation_ParameterSpecs{} }
func (m *Operation_ParameterSpecs) String() string            { return proto.CompactTextString(m) }
func (*Operation_ParameterSpecs) ProtoMessage()               {}
func (*Operation_ParameterSpecs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *Operation_ParameterSpecs) GetParameters() []*ParameterSpec {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// *
// Spec of a Experiment. Experiment represents a single optimization run over a feasible space.
// Each Experiment contains a configuration describing the feasible space, as well as a set of Trials.
// It is assumed that objective function f(x) does not change in the course of a Experiment.
type ExperimentSpec struct {
	ParameterSpecs       *ExperimentSpec_ParameterSpecs `protobuf:"bytes,1,opt,name=parameter_specs,json=parameterSpecs" json:"parameter_specs,omitempty"`
	Objective            *ObjectiveSpec                 `protobuf:"bytes,2,opt,name=objective" json:"objective,omitempty"`
	Algorithm            *AlgorithmSpec                 `protobuf:"bytes,3,opt,name=algorithm" json:"algorithm,omitempty"`
	TrialTemplate        string                         `protobuf:"bytes,4,opt,name=trial_template,json=trialTemplate" json:"trial_template,omitempty"`
	MetricsCollectorSpec string                         `protobuf:"bytes,5,opt,name=metrics_collector_spec,json=metricsCollectorSpec" json:"metrics_collector_spec,omitempty"`
	ParallelTrialCount   int32                          `protobuf:"varint,6,opt,name=parallel_trial_count,json=parallelTrialCount" json:"parallel_trial_count,omitempty"`
	MaxTrialCount        int32                          `protobuf:"varint,7,opt,name=max_trial_count,json=maxTrialCount" json:"max_trial_count,omitempty"`
	NasConfig            *NasConfig                     `protobuf:"bytes,8,opt,name=nas_config,json=nasConfig" json:"nas_config,omitempty"`
}

func (m *ExperimentSpec) Reset()                    { *m = ExperimentSpec{} }
func (m *ExperimentSpec) String() string            { return proto.CompactTextString(m) }
func (*ExperimentSpec) ProtoMessage()               {}
func (*ExperimentSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ExperimentSpec) GetParameterSpecs() *ExperimentSpec_ParameterSpecs {
	if m != nil {
		return m.ParameterSpecs
	}
	return nil
}

func (m *ExperimentSpec) GetObjective() *ObjectiveSpec {
	if m != nil {
		return m.Objective
	}
	return nil
}

func (m *ExperimentSpec) GetAlgorithm() *AlgorithmSpec {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *ExperimentSpec) GetTrialTemplate() string {
	if m != nil {
		return m.TrialTemplate
	}
	return ""
}

func (m *ExperimentSpec) GetMetricsCollectorSpec() string {
	if m != nil {
		return m.MetricsCollectorSpec
	}
	return ""
}

func (m *ExperimentSpec) GetParallelTrialCount() int32 {
	if m != nil {
		return m.ParallelTrialCount
	}
	return 0
}

func (m *ExperimentSpec) GetMaxTrialCount() int32 {
	if m != nil {
		return m.MaxTrialCount
	}
	return 0
}

func (m *ExperimentSpec) GetNasConfig() *NasConfig {
	if m != nil {
		return m.NasConfig
	}
	return nil
}

// *
// List of ParameterSpec
type ExperimentSpec_ParameterSpecs struct {
	Parameters []*ParameterSpec `protobuf:"bytes,1,rep,name=parameters" json:"parameters,omitempty"`
}

func (m *ExperimentSpec_ParameterSpecs) Reset()         { *m = ExperimentSpec_ParameterSpecs{} }
func (m *ExperimentSpec_ParameterSpecs) String() string { return proto.CompactTextString(m) }
func (*ExperimentSpec_ParameterSpecs) ProtoMessage()    {}
func (*ExperimentSpec_ParameterSpecs) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

func (m *ExperimentSpec_ParameterSpecs) GetParameters() []*ParameterSpec {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ExperimentStatus struct {
	StartTime      string                                   `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	CompletionTime string                                   `protobuf:"bytes,2,opt,name=completion_time,json=completionTime" json:"completion_time,omitempty"`
	Condition      ExperimentStatus_ExperimentConditionType `protobuf:"varint,3,opt,name=condition,enum=api.v1.alpha2.ExperimentStatus_ExperimentConditionType" json:"condition,omitempty"`
}

func (m *ExperimentStatus) Reset()                    { *m = ExperimentStatus{} }
func (m *ExperimentStatus) String() string            { return proto.CompactTextString(m) }
func (*ExperimentStatus) ProtoMessage()               {}
func (*ExperimentStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ExperimentStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *ExperimentStatus) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *ExperimentStatus) GetCondition() ExperimentStatus_ExperimentConditionType {
	if m != nil {
		return m.Condition
	}
	return ExperimentStatus_CREATED
}

type Experiment struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spec   *ExperimentSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status *ExperimentStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Experiment) Reset()                    { *m = Experiment{} }
func (m *Experiment) String() string            { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()               {}
func (*Experiment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Experiment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Experiment) GetSpec() *ExperimentSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Experiment) GetStatus() *ExperimentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ParameterAssignment struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ParameterAssignment) Reset()                    { *m = ParameterAssignment{} }
func (m *ParameterAssignment) String() string            { return proto.CompactTextString(m) }
func (*ParameterAssignment) ProtoMessage()               {}
func (*ParameterAssignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ParameterAssignment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterAssignment) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Metric struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MetricLog struct {
	TimeStamp string  `protobuf:"bytes,1,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Metric    *Metric `protobuf:"bytes,2,opt,name=metric" json:"metric,omitempty"`
}

func (m *MetricLog) Reset()                    { *m = MetricLog{} }
func (m *MetricLog) String() string            { return proto.CompactTextString(m) }
func (*MetricLog) ProtoMessage()               {}
func (*MetricLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MetricLog) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *MetricLog) GetMetric() *Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

type Observation struct {
	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *Observation) Reset()                    { *m = Observation{} }
func (m *Observation) String() string            { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()               {}
func (*Observation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Observation) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ObservationLog struct {
	MetricLogs []*MetricLog `protobuf:"bytes,1,rep,name=metric_logs,json=metricLogs" json:"metric_logs,omitempty"`
}

func (m *ObservationLog) Reset()                    { *m = ObservationLog{} }
func (m *ObservationLog) String() string            { return proto.CompactTextString(m) }
func (*ObservationLog) ProtoMessage()               {}
func (*ObservationLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ObservationLog) GetMetricLogs() []*MetricLog {
	if m != nil {
		return m.MetricLogs
	}
	return nil
}

type TrialSpec struct {
	ExperimentName       string                          `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	Objective            *ObjectiveSpec                  `protobuf:"bytes,2,opt,name=objective" json:"objective,omitempty"`
	ParameterAssignments *TrialSpec_ParameterAssignments `protobuf:"bytes,3,opt,name=parameter_assignments,json=parameterAssignments" json:"parameter_assignments,omitempty"`
	RunSpec              string                          `protobuf:"bytes,4,opt,name=run_spec,json=runSpec" json:"run_spec,omitempty"`
	MetricsCollectorSpec string                          `protobuf:"bytes,5,opt,name=metrics_collector_spec,json=metricsCollectorSpec" json:"metrics_collector_spec,omitempty"`
}

func (m *TrialSpec) Reset()                    { *m = TrialSpec{} }
func (m *TrialSpec) String() string            { return proto.CompactTextString(m) }
func (*TrialSpec) ProtoMessage()               {}
func (*TrialSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TrialSpec) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *TrialSpec) GetObjective() *ObjectiveSpec {
	if m != nil {
		return m.Objective
	}
	return nil
}

func (m *TrialSpec) GetParameterAssignments() *TrialSpec_ParameterAssignments {
	if m != nil {
		return m.ParameterAssignments
	}
	return nil
}

func (m *TrialSpec) GetRunSpec() string {
	if m != nil {
		return m.RunSpec
	}
	return ""
}

func (m *TrialSpec) GetMetricsCollectorSpec() string {
	if m != nil {
		return m.MetricsCollectorSpec
	}
	return ""
}

// *
// List of ParameterAssignment
type TrialSpec_ParameterAssignments struct {
	Assignments []*ParameterAssignment `protobuf:"bytes,1,rep,name=assignments" json:"assignments,omitempty"`
}

func (m *TrialSpec_ParameterAssignments) Reset()         { *m = TrialSpec_ParameterAssignments{} }
func (m *TrialSpec_ParameterAssignments) String() string { return proto.CompactTextString(m) }
func (*TrialSpec_ParameterAssignments) ProtoMessage()    {}
func (*TrialSpec_ParameterAssignments) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17, 0}
}

func (m *TrialSpec_ParameterAssignments) GetAssignments() []*ParameterAssignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type TrialStatus struct {
	StartTime      string                         `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	CompletionTime string                         `protobuf:"bytes,2,opt,name=completion_time,json=completionTime" json:"completion_time,omitempty"`
	Condition      TrialStatus_TrialConditionType `protobuf:"varint,3,opt,name=condition,enum=api.v1.alpha2.TrialStatus_TrialConditionType" json:"condition,omitempty"`
	Observation    *Observation                   `protobuf:"bytes,4,opt,name=observation" json:"observation,omitempty"`
}

func (m *TrialStatus) Reset()                    { *m = TrialStatus{} }
func (m *TrialStatus) String() string            { return proto.CompactTextString(m) }
func (*TrialStatus) ProtoMessage()               {}
func (*TrialStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TrialStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TrialStatus) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *TrialStatus) GetCondition() TrialStatus_TrialConditionType {
	if m != nil {
		return m.Condition
	}
	return TrialStatus_CREATED
}

func (m *TrialStatus) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

type Trial struct {
	Name   string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Spec   *TrialSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status *TrialStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Trial) Reset()                    { *m = Trial{} }
func (m *Trial) String() string            { return proto.CompactTextString(m) }
func (*Trial) ProtoMessage()               {}
func (*Trial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Trial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trial) GetSpec() *TrialSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Trial) GetStatus() *TrialStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RegisterExperimentRequest struct {
	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment" json:"experiment,omitempty"`
}

func (m *RegisterExperimentRequest) Reset()                    { *m = RegisterExperimentRequest{} }
func (m *RegisterExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterExperimentRequest) ProtoMessage()               {}
func (*RegisterExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RegisterExperimentRequest) GetExperiment() *Experiment {
	if m != nil {
		return m.Experiment
	}
	return nil
}

type RegisterExperimentReply struct {
}

func (m *RegisterExperimentReply) Reset()                    { *m = RegisterExperimentReply{} }
func (m *RegisterExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterExperimentReply) ProtoMessage()               {}
func (*RegisterExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type DeleteExperimentRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
}

func (m *DeleteExperimentRequest) Reset()                    { *m = DeleteExperimentRequest{} }
func (m *DeleteExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteExperimentRequest) ProtoMessage()               {}
func (*DeleteExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeleteExperimentRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type DeleteExperimentReply struct {
}

func (m *DeleteExperimentReply) Reset()                    { *m = DeleteExperimentReply{} }
func (m *DeleteExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteExperimentReply) ProtoMessage()               {}
func (*DeleteExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetExperimentRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
}

func (m *GetExperimentRequest) Reset()                    { *m = GetExperimentRequest{} }
func (m *GetExperimentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentRequest) ProtoMessage()               {}
func (*GetExperimentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetExperimentRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type GetExperimentReply struct {
	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment" json:"experiment,omitempty"`
}

func (m *GetExperimentReply) Reset()                    { *m = GetExperimentReply{} }
func (m *GetExperimentReply) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentReply) ProtoMessage()               {}
func (*GetExperimentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetExperimentReply) GetExperiment() *Experiment {
	if m != nil {
		return m.Experiment
	}
	return nil
}

type ExperimentSummary struct {
	ExperimentName string            `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	Status         *ExperimentStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ExperimentSummary) Reset()                    { *m = ExperimentSummary{} }
func (m *ExperimentSummary) String() string            { return proto.CompactTextString(m) }
func (*ExperimentSummary) ProtoMessage()               {}
func (*ExperimentSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ExperimentSummary) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *ExperimentSummary) GetStatus() *ExperimentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetExperimentListRequest struct {
}

func (m *GetExperimentListRequest) Reset()                    { *m = GetExperimentListRequest{} }
func (m *GetExperimentListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentListRequest) ProtoMessage()               {}
func (*GetExperimentListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type GetExperimentListReply struct {
	ExperimentSummaries []*ExperimentSummary `protobuf:"bytes,1,rep,name=experiment_summaries,json=experimentSummaries" json:"experiment_summaries,omitempty"`
}

func (m *GetExperimentListReply) Reset()                    { *m = GetExperimentListReply{} }
func (m *GetExperimentListReply) String() string            { return proto.CompactTextString(m) }
func (*GetExperimentListReply) ProtoMessage()               {}
func (*GetExperimentListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *GetExperimentListReply) GetExperimentSummaries() []*ExperimentSummary {
	if m != nil {
		return m.ExperimentSummaries
	}
	return nil
}

type UpdateExperimentStatusRequest struct {
	ExperimentName string            `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	NewStatus      *ExperimentStatus `protobuf:"bytes,2,opt,name=new_status,json=newStatus" json:"new_status,omitempty"`
}

func (m *UpdateExperimentStatusRequest) Reset()                    { *m = UpdateExperimentStatusRequest{} }
func (m *UpdateExperimentStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateExperimentStatusRequest) ProtoMessage()               {}
func (*UpdateExperimentStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UpdateExperimentStatusRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *UpdateExperimentStatusRequest) GetNewStatus() *ExperimentStatus {
	if m != nil {
		return m.NewStatus
	}
	return nil
}

type UpdateExperimentStatusReply struct {
}

func (m *UpdateExperimentStatusReply) Reset()                    { *m = UpdateExperimentStatusReply{} }
func (m *UpdateExperimentStatusReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateExperimentStatusReply) ProtoMessage()               {}
func (*UpdateExperimentStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type UpdateAlgorithmExtraSettingsRequest struct {
	ExperimentName         string              `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	ExtraAlgorithmSettings []*AlgorithmSetting `protobuf:"bytes,2,rep,name=extra_algorithm_settings,json=extraAlgorithmSettings" json:"extra_algorithm_settings,omitempty"`
}

func (m *UpdateAlgorithmExtraSettingsRequest) Reset()         { *m = UpdateAlgorithmExtraSettingsRequest{} }
func (m *UpdateAlgorithmExtraSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAlgorithmExtraSettingsRequest) ProtoMessage()    {}
func (*UpdateAlgorithmExtraSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{31}
}

func (m *UpdateAlgorithmExtraSettingsRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *UpdateAlgorithmExtraSettingsRequest) GetExtraAlgorithmSettings() []*AlgorithmSetting {
	if m != nil {
		return m.ExtraAlgorithmSettings
	}
	return nil
}

type UpdateAlgorithmExtraSettingsReply struct {
}

func (m *UpdateAlgorithmExtraSettingsReply) Reset()         { *m = UpdateAlgorithmExtraSettingsReply{} }
func (m *UpdateAlgorithmExtraSettingsReply) String() string { return proto.CompactTextString(m) }
func (*UpdateAlgorithmExtraSettingsReply) ProtoMessage()    {}
func (*UpdateAlgorithmExtraSettingsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32}
}

type GetAlgorithmExtraSettingsRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
}

func (m *GetAlgorithmExtraSettingsRequest) Reset()         { *m = GetAlgorithmExtraSettingsRequest{} }
func (m *GetAlgorithmExtraSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlgorithmExtraSettingsRequest) ProtoMessage()    {}
func (*GetAlgorithmExtraSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33}
}

func (m *GetAlgorithmExtraSettingsRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type GetAlgorithmExtraSettingsReply struct {
	ExtraAlgorithmSettings []*AlgorithmSetting `protobuf:"bytes,1,rep,name=extra_algorithm_settings,json=extraAlgorithmSettings" json:"extra_algorithm_settings,omitempty"`
}

func (m *GetAlgorithmExtraSettingsReply) Reset()                    { *m = GetAlgorithmExtraSettingsReply{} }
func (m *GetAlgorithmExtraSettingsReply) String() string            { return proto.CompactTextString(m) }
func (*GetAlgorithmExtraSettingsReply) ProtoMessage()               {}
func (*GetAlgorithmExtraSettingsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *GetAlgorithmExtraSettingsReply) GetExtraAlgorithmSettings() []*AlgorithmSetting {
	if m != nil {
		return m.ExtraAlgorithmSettings
	}
	return nil
}

type RegisterTrialRequest struct {
	Trial *Trial `protobuf:"bytes,1,opt,name=trial" json:"trial,omitempty"`
}

func (m *RegisterTrialRequest) Reset()                    { *m = RegisterTrialRequest{} }
func (m *RegisterTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterTrialRequest) ProtoMessage()               {}
func (*RegisterTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RegisterTrialRequest) GetTrial() *Trial {
	if m != nil {
		return m.Trial
	}
	return nil
}

type RegisterTrialReply struct {
}

func (m *RegisterTrialReply) Reset()                    { *m = RegisterTrialReply{} }
func (m *RegisterTrialReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterTrialReply) ProtoMessage()               {}
func (*RegisterTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type DeleteTrialRequest struct {
	TrialName string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
}

func (m *DeleteTrialRequest) Reset()                    { *m = DeleteTrialRequest{} }
func (m *DeleteTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTrialRequest) ProtoMessage()               {}
func (*DeleteTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *DeleteTrialRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

type DeleteTrialReply struct {
}

func (m *DeleteTrialReply) Reset()                    { *m = DeleteTrialReply{} }
func (m *DeleteTrialReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteTrialReply) ProtoMessage()               {}
func (*DeleteTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type GetTrialListRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	Filter         string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
}

func (m *GetTrialListRequest) Reset()                    { *m = GetTrialListRequest{} }
func (m *GetTrialListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTrialListRequest) ProtoMessage()               {}
func (*GetTrialListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *GetTrialListRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *GetTrialListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type GetTrialListReply struct {
	Trials []*Trial `protobuf:"bytes,1,rep,name=trials" json:"trials,omitempty"`
}

func (m *GetTrialListReply) Reset()                    { *m = GetTrialListReply{} }
func (m *GetTrialListReply) String() string            { return proto.CompactTextString(m) }
func (*GetTrialListReply) ProtoMessage()               {}
func (*GetTrialListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *GetTrialListReply) GetTrials() []*Trial {
	if m != nil {
		return m.Trials
	}
	return nil
}

type GetTrialRequest struct {
	TrialName string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
}

func (m *GetTrialRequest) Reset()                    { *m = GetTrialRequest{} }
func (m *GetTrialRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTrialRequest) ProtoMessage()               {}
func (*GetTrialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *GetTrialRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

type GetTrialReply struct {
	Trial *Trial `protobuf:"bytes,1,opt,name=trial" json:"trial,omitempty"`
}

func (m *GetTrialReply) Reset()                    { *m = GetTrialReply{} }
func (m *GetTrialReply) String() string            { return proto.CompactTextString(m) }
func (*GetTrialReply) ProtoMessage()               {}
func (*GetTrialReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *GetTrialReply) GetTrial() *Trial {
	if m != nil {
		return m.Trial
	}
	return nil
}

type UpdateTrialStatusRequest struct {
	TrialName string       `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
	NewStatus *TrialStatus `protobuf:"bytes,2,opt,name=new_status,json=newStatus" json:"new_status,omitempty"`
}

func (m *UpdateTrialStatusRequest) Reset()                    { *m = UpdateTrialStatusRequest{} }
func (m *UpdateTrialStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTrialStatusRequest) ProtoMessage()               {}
func (*UpdateTrialStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *UpdateTrialStatusRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

func (m *UpdateTrialStatusRequest) GetNewStatus() *TrialStatus {
	if m != nil {
		return m.NewStatus
	}
	return nil
}

type UpdateTrialStatusReply struct {
}

func (m *UpdateTrialStatusReply) Reset()                    { *m = UpdateTrialStatusReply{} }
func (m *UpdateTrialStatusReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateTrialStatusReply) ProtoMessage()               {}
func (*UpdateTrialStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type ReportObservationLogRequest struct {
	TrialName      string          `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
	ObservationLog *ObservationLog `protobuf:"bytes,2,opt,name=observation_log,json=observationLog" json:"observation_log,omitempty"`
}

func (m *ReportObservationLogRequest) Reset()                    { *m = ReportObservationLogRequest{} }
func (m *ReportObservationLogRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportObservationLogRequest) ProtoMessage()               {}
func (*ReportObservationLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *ReportObservationLogRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

func (m *ReportObservationLogRequest) GetObservationLog() *ObservationLog {
	if m != nil {
		return m.ObservationLog
	}
	return nil
}

type ReportObservationLogReply struct {
}

func (m *ReportObservationLogReply) Reset()                    { *m = ReportObservationLogReply{} }
func (m *ReportObservationLogReply) String() string            { return proto.CompactTextString(m) }
func (*ReportObservationLogReply) ProtoMessage()               {}
func (*ReportObservationLogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

type GetObservationLogRequest struct {
	TrialName  string `protobuf:"bytes,1,opt,name=trial_name,json=trialName" json:"trial_name,omitempty"`
	MetricName string `protobuf:"bytes,2,opt,name=metric_name,json=metricName" json:"metric_name,omitempty"`
	StartTime  string `protobuf:"bytes,3,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime    string `protobuf:"bytes,4,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *GetObservationLogRequest) Reset()                    { *m = GetObservationLogRequest{} }
func (m *GetObservationLogRequest) String() string            { return proto.CompactTextString(m) }
func (*GetObservationLogRequest) ProtoMessage()               {}
func (*GetObservationLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *GetObservationLogRequest) GetTrialName() string {
	if m != nil {
		return m.TrialName
	}
	return ""
}

func (m *GetObservationLogRequest) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *GetObservationLogRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetObservationLogRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GetObservationLogReply struct {
	ObservationLog *ObservationLog `protobuf:"bytes,1,opt,name=observation_log,json=observationLog" json:"observation_log,omitempty"`
}

func (m *GetObservationLogReply) Reset()                    { *m = GetObservationLogReply{} }
func (m *GetObservationLogReply) String() string            { return proto.CompactTextString(m) }
func (*GetObservationLogReply) ProtoMessage()               {}
func (*GetObservationLogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *GetObservationLogReply) GetObservationLog() *ObservationLog {
	if m != nil {
		return m.ObservationLog
	}
	return nil
}

type GetSuggestionsRequest struct {
	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName" json:"experiment_name,omitempty"`
	AlgorithmName  string `protobuf:"bytes,2,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
	RequestNumber  int32  `protobuf:"varint,3,opt,name=request_number,json=requestNumber" json:"request_number,omitempty"`
}

func (m *GetSuggestionsRequest) Reset()                    { *m = GetSuggestionsRequest{} }
func (m *GetSuggestionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestionsRequest) ProtoMessage()               {}
func (*GetSuggestionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetSuggestionsRequest) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

func (m *GetSuggestionsRequest) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *GetSuggestionsRequest) GetRequestNumber() int32 {
	if m != nil {
		return m.RequestNumber
	}
	return 0
}

type GetSuggestionsReply struct {
	Trials *dbif_v1_alpha2.Trial `protobuf:"bytes,1,opt,name=trials" json:"trials,omitempty"`
}

func (m *GetSuggestionsReply) Reset()                    { *m = GetSuggestionsReply{} }
func (m *GetSuggestionsReply) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestionsReply) ProtoMessage()               {}
func (*GetSuggestionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetSuggestionsReply) GetTrials() *dbif_v1_alpha2.Trial {
	if m != nil {
		return m.Trials
	}
	return nil
}

type ValidateAlgorithmSettingsRequest struct {
	ExperimentSpec *dbif_v1_alpha2.ExperimentSpec `protobuf:"bytes,1,opt,name=experiment_spec,json=experimentSpec" json:"experiment_spec,omitempty"`
	AlgorithmName  string                         `protobuf:"bytes,2,opt,name=algorithm_name,json=algorithmName" json:"algorithm_name,omitempty"`
}

func (m *ValidateAlgorithmSettingsRequest) Reset()         { *m = ValidateAlgorithmSettingsRequest{} }
func (m *ValidateAlgorithmSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateAlgorithmSettingsRequest) ProtoMessage()    {}
func (*ValidateAlgorithmSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *ValidateAlgorithmSettingsRequest) GetExperimentSpec() *dbif_v1_alpha2.ExperimentSpec {
	if m != nil {
		return m.ExperimentSpec
	}
	return nil
}

func (m *ValidateAlgorithmSettingsRequest) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

// *
// Return INVALID_ARGUMENT Error if Algorithm Settings are not Valid
type ValidateAlgorithmSettingsReply struct {
}

func (m *ValidateAlgorithmSettingsReply) Reset()                    { *m = ValidateAlgorithmSettingsReply{} }
func (m *ValidateAlgorithmSettingsReply) String() string            { return proto.CompactTextString(m) }
func (*ValidateAlgorithmSettingsReply) ProtoMessage()               {}
func (*ValidateAlgorithmSettingsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*GetSuggestionsRequest)(nil), "api.v1.alpha2.GetSuggestionsRequest")
	proto.RegisterType((*GetSuggestionsReply)(nil), "api.v1.alpha2.GetSuggestionsReply")
	proto.RegisterType((*ValidateAlgorithmSettingsRequest)(nil), "api.v1.alpha2.ValidateAlgorithmSettingsRequest")
	proto.RegisterType((*ValidateAlgorithmSettingsReply)(nil), "api.v1.alpha2.ValidateAlgorithmSettingsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	// *
	// Get Suggestions from a Suggestion service.
	GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error)
	// *
	// Validate AlgorithmSettings in an Experiment.
	// Suggestion service should return INVALID_ARGUMENT Error when the parameter is invalid
	ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error) {
	out := new(GetSuggestionsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/GetSuggestions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error) {
	out := new(ValidateAlgorithmSettingsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Manager/ValidateAlgorithmSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	// *
	// Get Suggestions from a Suggestion service.
	GetSuggestions(context.Context, *GetSuggestionsRequest) (*GetSuggestionsReply, error)
	// *
	// Validate AlgorithmSettings in an Experiment.
	// Suggestion service should return INVALID_ARGUMENT Error when the parameter is invalid
	ValidateAlgorithmSettings(context.Context, *ValidateAlgorithmSettingsRequest) (*ValidateAlgorithmSettingsReply, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetSuggestions(ctx, req.(*GetSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ValidateAlgorithmSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAlgorithmSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ValidateAlgorithmSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Manager/ValidateAlgorithmSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ValidateAlgorithmSettings(ctx, req.(*ValidateAlgorithmSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _Manager_GetSuggestions_Handler,
		},
		{
			MethodName: "ValidateAlgorithmSettings",
			Handler:    _Manager_ValidateAlgorithmSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for Suggestion service

type SuggestionClient interface {
	GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error)
	ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error)
}

type suggestionClient struct {
	cc *grpc.ClientConn
}

func NewSuggestionClient(cc *grpc.ClientConn) SuggestionClient {
	return &suggestionClient{cc}
}

func (c *suggestionClient) GetSuggestions(ctx context.Context, in *GetSuggestionsRequest, opts ...grpc.CallOption) (*GetSuggestionsReply, error) {
	out := new(GetSuggestionsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Suggestion/GetSuggestions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suggestionClient) ValidateAlgorithmSettings(ctx context.Context, in *ValidateAlgorithmSettingsRequest, opts ...grpc.CallOption) (*ValidateAlgorithmSettingsReply, error) {
	out := new(ValidateAlgorithmSettingsReply)
	err := grpc.Invoke(ctx, "/api.v1.alpha2.Suggestion/ValidateAlgorithmSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Suggestion service

type SuggestionServer interface {
	GetSuggestions(context.Context, *GetSuggestionsRequest) (*GetSuggestionsReply, error)
	ValidateAlgorithmSettings(context.Context, *ValidateAlgorithmSettingsRequest) (*ValidateAlgorithmSettingsReply, error)
}

func RegisterSuggestionServer(s *grpc.Server, srv SuggestionServer) {
	s.RegisterService(&_Suggestion_serviceDesc, srv)
}

func _Suggestion_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Suggestion/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServer).GetSuggestions(ctx, req.(*GetSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Suggestion_ValidateAlgorithmSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAlgorithmSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServer).ValidateAlgorithmSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.alpha2.Suggestion/ValidateAlgorithmSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServer).ValidateAlgorithmSettings(ctx, req.(*ValidateAlgorithmSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Suggestion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.Suggestion",
	HandlerType: (*SuggestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _Suggestion_GetSuggestions_Handler,
		},
		{
			MethodName: "ValidateAlgorithmSettings",
			Handler:    _Suggestion_ValidateAlgorithmSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for EarlyStopping service

type EarlyStoppingClient interface {
}

type earlyStoppingClient struct {
	cc *grpc.ClientConn
}

func NewEarlyStoppingClient(cc *grpc.ClientConn) EarlyStoppingClient {
	return &earlyStoppingClient{cc}
}

// Server API for EarlyStopping service

type EarlyStoppingServer interface {
}

func RegisterEarlyStoppingServer(s *grpc.Server, srv EarlyStoppingServer) {
	s.RegisterService(&_EarlyStopping_serviceDesc, srv)
}

var _EarlyStopping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.alpha2.EarlyStopping",
	HandlerType: (*EarlyStoppingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x5a, 0xdd, 0x6f, 0x1b, 0x59,
	0x15, 0xdf, 0xb1, 0xf3, 0x51, 0x1f, 0xd7, 0x8e, 0x73, 0x93, 0xb4, 0x8e, 0xfb, 0x11, 0xf7, 0xf6,
	0x2b, 0x64, 0xdb, 0xa4, 0xf5, 0x2e, 0xdb, 0xdd, 0x6c, 0xd9, 0xdd, 0xd4, 0x71, 0xa3, 0xa8, 0xa9,
	0x53, 0x8d, 0x9d, 0x42, 0x17, 0xa4, 0x61, 0xe2, 0xde, 0xba, 0x03, 0xe3, 0x99, 0x61, 0x66, 0xdc,
	0x4d, 0xa8, 0x2a, 0xa1, 0xc2, 0x03, 0x08, 0xa8, 0x84, 0xe0, 0x05, 0x90, 0xe0, 0x0d, 0x89, 0x07,
	0x78, 0xe2, 0x95, 0x07, 0x24, 0x1e, 0x79, 0xe3, 0xe3, 0x2f, 0x80, 0xff, 0x03, 0xdd, 0x33, 0xdf,
	0x5f, 0x8e, 0xd3, 0x16, 0xf1, 0x36, 0x73, 0xef, 0xef, 0x9e, 0xfb, 0x3b, 0xe7, 0x9e, 0xf3, 0xbb,
	0xc7, 0x93, 0x40, 0x41, 0x36, 0x94, 0x55, 0xc3, 0xd4, 0x6d, 0x9d, 0x94, 0xf8, 0xe3, 0xb3, 0x9b,
	0xab, 0xb2, 0x6a, 0x3c, 0x95, 0x1b, 0xb5, 0xb3, 0x7d, 0x5d, 0xef, 0xab, 0x6c, 0x4d, 0x36, 0x94,
	0x35, 0x59, 0xd3, 0x74, 0x5b, 0xb6, 0x15, 0x5d, 0xb3, 0x1c, 0x30, 0xfd, 0x3a, 0x94, 0xee, 0x32,
	0xd9, 0x52, 0xf6, 0x55, 0xd6, 0x31, 0xe4, 0x1e, 0x23, 0x15, 0xc8, 0x0f, 0xe4, 0x83, 0xaa, 0x50,
	0x17, 0x96, 0x0b, 0x22, 0x7f, 0xc4, 0x11, 0x45, 0xab, 0xe6, 0xdc, 0x11, 0x45, 0x23, 0x04, 0x26,
	0x54, 0xc5, 0xb2, 0xab, 0xf9, 0x7a, 0x7e, 0xb9, 0x20, 0xe2, 0x33, 0x1f, 0xb3, 0x6c, 0x66, 0x54,
	0x27, 0x10, 0x86, 0xcf, 0xf4, 0x0f, 0x02, 0x94, 0x1e, 0xc8, 0xa6, 0x3c, 0x60, 0x36, 0x33, 0x3b,
	0x06, 0xeb, 0x71, 0x94, 0x26, 0x0f, 0x98, 0x6b, 0x1e, 0x9f, 0x49, 0x13, 0xca, 0x86, 0x07, 0x92,
	0xec, 0x43, 0x83, 0xe1, 0x56, 0xe5, 0xc6, 0xd9, 0xd5, 0x88, 0x23, 0xab, 0xbe, 0xa5, 0xee, 0xa1,
	0xc1, 0xc4, 0x92, 0x11, 0x7e, 0xe5, 0x46, 0x9e, 0xb8, 0x7e, 0x48, 0x16, 0x77, 0xa4, 0x9a, 0xaf,
	0x0b, 0xcb, 0xc5, 0x84, 0x91, 0x88, 0xb3, 0x62, 0xe9, 0x49, 0xf8, 0x95, 0xfe, 0x45, 0x80, 0xd2,
	0xee, 0xfe, 0xb7, 0x58, 0xcf, 0x56, 0x9e, 0x31, 0xe4, 0x7b, 0x03, 0x26, 0x90, 0x91, 0x90, 0xca,
	0xc8, 0xc7, 0x22, 0x23, 0x44, 0x72, 0x0f, 0xfb, 0xba, 0xac, 0xa2, 0x0f, 0x39, 0x11, 0x9f, 0x49,
	0x03, 0x16, 0x74, 0x0f, 0x2a, 0x0d, 0x98, 0x6d, 0x2a, 0x3d, 0x09, 0xc3, 0x90, 0xc7, 0x30, 0xcc,
	0xf9, 0x93, 0xf7, 0x71, 0xae, 0xcd, 0xa3, 0xf2, 0x01, 0x9c, 0x96, 0x1f, 0x3f, 0x56, 0xf8, 0x59,
	0xc9, 0x6a, 0x78, 0x91, 0x55, 0x9d, 0xc0, 0xb0, 0x2f, 0x04, 0xd3, 0xc1, 0x32, 0x8b, 0xde, 0x86,
	0xca, 0x86, 0xda, 0xd7, 0x4d, 0xc5, 0x7e, 0x3a, 0xe8, 0x30, 0xdb, 0x56, 0xb4, 0x7e, 0x6a, 0xd4,
	0xe7, 0x61, 0xf2, 0x99, 0xac, 0x0e, 0x99, 0x7b, 0xae, 0xce, 0x0b, 0x9d, 0x83, 0xd9, 0x96, 0x6c,
	0xaa, 0x87, 0x1d, 0x5b, 0x37, 0x0c, 0x45, 0xeb, 0xf3, 0x20, 0xd0, 0x7f, 0x09, 0x50, 0x0a, 0x6c,
	0xf2, 0xb0, 0x5c, 0x86, 0xb2, 0xec, 0x0d, 0x48, 0x21, 0xd3, 0x25, 0x7f, 0x14, 0x7d, 0xd8, 0x81,
	0xd9, 0x00, 0x66, 0x39, 0x64, 0xaa, 0xb9, 0x7a, 0x7e, 0xb9, 0xd8, 0x58, 0x8a, 0x85, 0x32, 0xce,
	0x59, 0xac, 0xc8, 0x71, 0x2f, 0x1e, 0xc0, 0x1c, 0xe3, 0xdc, 0x24, 0xcb, 0x25, 0x27, 0x59, 0x06,
	0xeb, 0xb9, 0xe7, 0x5c, 0x8f, 0xd9, 0x4b, 0x78, 0x21, 0xce, 0xb2, 0x84, 0x63, 0xff, 0x14, 0xa0,
	0xd0, 0x96, 0xad, 0xa6, 0xae, 0x3d, 0x51, 0xfa, 0xe4, 0x2b, 0x70, 0xb2, 0x6f, 0xca, 0xc6, 0x53,
	0xa9, 0x87, 0xef, 0xe8, 0x52, 0xb1, 0x51, 0x8b, 0x19, 0xde, 0xe2, 0x10, 0x67, 0x85, 0x58, 0xec,
	0x07, 0x2f, 0xa4, 0x09, 0xa0, 0x1b, 0xcc, 0x74, 0xaa, 0x0b, 0xa3, 0x5a, 0x6c, 0x5c, 0x8c, 0x2d,
	0xf6, 0x37, 0x5b, 0xdd, 0xf5, 0xa1, 0x62, 0x68, 0x59, 0x6d, 0x13, 0x20, 0x98, 0x21, 0x1f, 0x40,
	0xc1, 0x9f, 0xab, 0x0a, 0x18, 0xb7, 0x6a, 0x3c, 0x05, 0xbd, 0x79, 0x31, 0x80, 0x52, 0x03, 0x8a,
	0x21, 0x9a, 0xe4, 0x1c, 0x80, 0x36, 0x1c, 0x48, 0xaa, 0x7c, 0xc8, 0x4c, 0x0b, 0xdd, 0x9a, 0x14,
	0x0b, 0xda, 0x70, 0xb0, 0x83, 0x03, 0x64, 0x09, 0x8a, 0x8a, 0x66, 0x0c, 0x6d, 0xc9, 0x52, 0xbe,
	0xcb, 0x2c, 0x3c, 0x9f, 0x49, 0x11, 0x70, 0xa8, 0xc3, 0x47, 0xc8, 0x05, 0x38, 0xa9, 0x0f, 0xed,
	0x00, 0x91, 0x47, 0x44, 0xd1, 0x19, 0x43, 0x08, 0xfd, 0x87, 0x00, 0x05, 0x9f, 0x0a, 0x4f, 0x0f,
	0x9f, 0x8c, 0xe4, 0xd7, 0x4f, 0x41, 0x2c, 0xf9, 0xa3, 0x58, 0xb3, 0x0f, 0x60, 0x26, 0x28, 0x7c,
	0x7e, 0x96, 0x5e, 0xd8, 0xae, 0x66, 0x39, 0xb9, 0x1a, 0x51, 0x13, 0x4b, 0x0c, 0x84, 0x03, 0xdf,
	0x6b, 0x6d, 0x28, 0x47, 0x11, 0xe4, 0x36, 0x80, 0x8f, 0xb1, 0xdc, 0x18, 0x66, 0x0a, 0x0b, 0xe6,
	0x49, 0x08, 0x4f, 0x7f, 0x3b, 0x01, 0xe5, 0xd6, 0x81, 0xc1, 0x4c, 0x65, 0xc0, 0x34, 0x1b, 0x53,
	0x7f, 0x2f, 0x49, 0xda, 0x49, 0x94, 0x6b, 0xf1, 0x0c, 0x8c, 0xac, 0x3b, 0x82, 0x39, 0x59, 0x87,
	0x82, 0xaf, 0x02, 0x6e, 0x14, 0x32, 0xd5, 0x06, 0x69, 0x06, 0x70, 0xbe, 0xd6, 0x2f, 0x96, 0x0c,
	0xd9, 0x8b, 0x94, 0xaf, 0x18, 0xc0, 0xf9, 0x51, 0xd9, 0xa6, 0x22, 0xab, 0x92, 0xcd, 0x06, 0x86,
	0x2a, 0xdb, 0xcc, 0x15, 0xf0, 0x12, 0x8e, 0x76, 0xdd, 0x41, 0xf2, 0x3e, 0x9c, 0x72, 0x24, 0xc8,
	0x92, 0x7a, 0xba, 0xaa, 0xb2, 0x9e, 0xad, 0x3b, 0xde, 0x57, 0x27, 0x11, 0x3e, 0xef, 0xce, 0x36,
	0xbd, 0x49, 0x57, 0x3d, 0xe7, 0xb9, 0x9b, 0xaa, 0xca, 0x54, 0xc9, 0xd9, 0xa5, 0xa7, 0x0f, 0x35,
	0xbb, 0x3a, 0x85, 0x29, 0x48, 0xbc, 0xb9, 0x2e, 0x9f, 0x6a, 0xf2, 0x19, 0x72, 0x05, 0x66, 0x06,
	0xf2, 0x41, 0x04, 0x3c, 0x8d, 0xe0, 0xd2, 0x40, 0x3e, 0x08, 0xe1, 0x6e, 0x01, 0x68, 0xb2, 0xe5,
	0x55, 0xea, 0x09, 0xf4, 0xb9, 0x9a, 0x55, 0x6c, 0x62, 0x41, 0xf3, 0x1e, 0xdf, 0x7a, 0x86, 0xfc,
	0x26, 0x07, 0x95, 0xd0, 0x49, 0xdb, 0xb2, 0x3d, 0xb4, 0x78, 0xc1, 0x59, 0xb6, 0x6c, 0xda, 0x92,
	0xad, 0xf8, 0xd2, 0x58, 0xc0, 0x91, 0xae, 0x32, 0x60, 0xe4, 0x2a, 0xcc, 0xf4, 0xf4, 0x81, 0xa1,
	0x32, 0xa7, 0x3e, 0x38, 0xc6, 0x11, 0xe1, 0x72, 0x30, 0x8c, 0xc0, 0x3d, 0x28, 0xf4, 0x74, 0xcd,
	0x51, 0x79, 0x3c, 0xd8, 0x72, 0xe3, 0x56, 0x76, 0x96, 0xe1, 0xde, 0xa1, 0x81, 0xa6, 0xb7, 0x14,
	0x6f, 0xa7, 0xc0, 0x12, 0xfd, 0x36, 0x9c, 0xce, 0x40, 0x91, 0x22, 0x4c, 0x37, 0xc5, 0xd6, 0x46,
	0xb7, 0xb5, 0x59, 0x79, 0x87, 0xbf, 0x88, 0x7b, 0xed, 0xf6, 0x76, 0x7b, 0xab, 0x22, 0x90, 0x32,
	0x80, 0xd8, 0xea, 0x74, 0x37, 0xc4, 0x2e, 0x7f, 0xcf, 0x91, 0x12, 0x14, 0x3a, 0x7b, 0xcd, 0x66,
	0xab, 0xb5, 0xd9, 0xda, 0xac, 0xe4, 0x09, 0xc0, 0xd4, 0xdd, 0x8d, 0xed, 0x9d, 0xd6, 0x66, 0x65,
	0x82, 0xaf, 0xdb, 0x6b, 0xdf, 0x6b, 0xef, 0x7e, 0xb5, 0x5d, 0x99, 0xa4, 0x3f, 0x11, 0x00, 0x82,
	0xdd, 0x52, 0xaf, 0xa2, 0x9b, 0x30, 0x81, 0xa9, 0xe4, 0xa4, 0xfd, 0xb9, 0x91, 0x75, 0x24, 0x22,
	0x94, 0xdc, 0x82, 0x29, 0x0b, 0xfd, 0x75, 0xf3, 0x7d, 0xe9, 0x88, 0xb0, 0x88, 0x2e, 0x9c, 0x7e,
	0x0a, 0x73, 0xfe, 0x61, 0x6e, 0x58, 0x96, 0xd2, 0xd7, 0x32, 0x69, 0xa5, 0xdf, 0x90, 0x0d, 0x98,
	0x72, 0xae, 0xdb, 0x63, 0xac, 0x79, 0x04, 0x05, 0x67, 0xcd, 0x8e, 0x8e, 0x6a, 0xcc, 0x8f, 0x5c,
	0xb2, 0x6c, 0x79, 0x60, 0x78, 0xc9, 0xc1, 0x47, 0x3a, 0x7c, 0x80, 0x5c, 0x87, 0x29, 0xa7, 0x96,
	0xdc, 0x70, 0x2c, 0xc4, 0x3c, 0x73, 0x0c, 0x89, 0x2e, 0x88, 0x7e, 0x02, 0xc5, 0xdd, 0x7d, 0x8b,
	0x99, 0xcf, 0x1c, 0xe5, 0x5d, 0x83, 0x69, 0xb7, 0x12, 0xdd, 0x4c, 0xce, 0x58, 0xee, 0xa1, 0xe8,
	0x3d, 0x28, 0x87, 0xd6, 0x73, 0x7e, 0x1f, 0x41, 0xd1, 0xed, 0x36, 0x54, 0xbd, 0x6f, 0x65, 0x5c,
	0x3b, 0xbe, 0x3b, 0x22, 0x0c, 0xbc, 0x47, 0x8b, 0x7e, 0x3f, 0x0f, 0x05, 0x2c, 0x52, 0xac, 0xfe,
	0xab, 0x30, 0xc3, 0xfc, 0x63, 0x08, 0x77, 0x09, 0xe5, 0x60, 0x18, 0xdb, 0x84, 0x37, 0xd1, 0xbe,
	0x7d, 0x58, 0x08, 0xe4, 0x58, 0xf6, 0x0f, 0xd4, 0xcb, 0x8b, 0xeb, 0x31, 0x3b, 0x3e, 0xbb, 0xd5,
	0x94, 0x2c, 0xb0, 0xc4, 0x79, 0x23, 0x65, 0x94, 0x2c, 0xc2, 0x09, 0x73, 0xa8, 0x39, 0x72, 0xe7,
	0xa8, 0xe3, 0xb4, 0x39, 0xd4, 0xd0, 0xc7, 0xd7, 0xd2, 0xc5, 0xda, 0x37, 0x60, 0x3e, 0x6d, 0x7b,
	0xb2, 0x09, 0xc5, 0xb0, 0x0b, 0x4e, 0xe8, 0x69, 0x96, 0x16, 0x05, 0x2b, 0xc5, 0xf0, 0x32, 0xfa,
	0xd7, 0x1c, 0x14, 0x1d, 0x3f, 0xdf, 0xae, 0x1a, 0xdd, 0x4b, 0xaa, 0x51, 0x7a, 0x78, 0x1d, 0x21,
	0x72, 0xd5, 0x3a, 0x5d, 0x83, 0xc8, 0x6d, 0x28, 0xea, 0x41, 0xde, 0x61, 0x58, 0x93, 0xbd, 0x56,
	0x28, 0x33, 0xc5, 0x30, 0x9c, 0xee, 0x03, 0x49, 0x9a, 0x1f, 0x21, 0x5e, 0x11, 0xb1, 0xca, 0x71,
	0xb1, 0xba, 0xb7, 0xbd, 0xb3, 0x33, 0x5a, 0xb8, 0x5e, 0xc0, 0x24, 0xee, 0x91, 0x5a, 0xe7, 0xd7,
	0x22, 0x92, 0x55, 0xcd, 0xca, 0x32, 0x57, 0xad, 0x1a, 0x31, 0xb5, 0xaa, 0x65, 0x87, 0xcd, 0x17,
	0xaa, 0x87, 0xb0, 0x28, 0xb2, 0xbe, 0x62, 0xd9, 0xcc, 0x0c, 0xc4, 0x4c, 0x64, 0xdf, 0x19, 0x32,
	0xcb, 0x26, 0x1f, 0x01, 0x04, 0x35, 0xe4, 0xf6, 0x1f, 0x8b, 0x99, 0x12, 0x28, 0x86, 0xc0, 0x74,
	0x11, 0x4e, 0xa7, 0xd9, 0x35, 0xd4, 0x43, 0x7a, 0x07, 0x4e, 0x6f, 0x32, 0x95, 0xd9, 0x2c, 0xb9,
	0xe1, 0xb8, 0xb5, 0x4c, 0x4f, 0xc3, 0x42, 0xd2, 0x06, 0x37, 0xfe, 0x29, 0xcc, 0x6f, 0x31, 0xfb,
	0x0d, 0x2c, 0xef, 0x02, 0x89, 0x19, 0x30, 0xd4, 0xc3, 0x37, 0x89, 0xc4, 0x10, 0x66, 0x43, 0xd7,
	0xc4, 0x70, 0x30, 0x90, 0xcd, 0xc3, 0xf1, 0x45, 0x2b, 0xb8, 0x81, 0x72, 0xc7, 0xbb, 0x81, 0x6a,
	0x50, 0x8d, 0xf8, 0xb1, 0xa3, 0x58, 0x5e, 0x30, 0xe8, 0x00, 0x4e, 0xa5, 0xcc, 0x71, 0x3f, 0x3b,
	0x30, 0x1f, 0xe2, 0x65, 0x21, 0x5b, 0x85, 0x79, 0x1a, 0x51, 0xcf, 0xde, 0xdc, 0xf1, 0x4b, 0x9c,
	0x63, 0xb1, 0x21, 0x85, 0x59, 0xf4, 0x87, 0x02, 0x9c, 0xdb, 0x33, 0x1e, 0xcb, 0xe1, 0xd3, 0x72,
	0xd9, 0x1e, 0xf3, 0x74, 0xc8, 0x27, 0x00, 0x1a, 0xfb, 0x42, 0x3a, 0x5e, 0x48, 0x0a, 0x1a, 0xfb,
	0xc2, 0x79, 0xa4, 0xe7, 0xe0, 0x4c, 0x16, 0x13, 0x9e, 0x3d, 0xbf, 0x17, 0xe0, 0xa2, 0x33, 0xef,
	0x77, 0xb2, 0xad, 0x03, 0xdb, 0x94, 0xdd, 0xdf, 0x86, 0xc7, 0xe7, 0xfb, 0x08, 0xaa, 0x8c, 0x1b,
	0x90, 0x12, 0x3f, 0x50, 0xad, 0x71, 0x7f, 0xa1, 0x9e, 0x42, 0x03, 0xf1, 0x61, 0x8b, 0x5e, 0x84,
	0x0b, 0xa3, 0xa9, 0x72, 0x87, 0xee, 0x41, 0x7d, 0x8b, 0xd9, 0x6f, 0xc7, 0x19, 0xfa, 0x1c, 0xce,
	0x8f, 0x30, 0xc6, 0xd3, 0x67, 0x94, 0xbb, 0xc2, 0x9b, 0xb9, 0x7b, 0x07, 0xe6, 0x3d, 0x41, 0x41,
	0x1d, 0xf3, 0xd8, 0xaf, 0xc0, 0x24, 0xb6, 0xf1, 0x6e, 0x51, 0xce, 0xa7, 0x69, 0x9e, 0xe8, 0x40,
	0xe8, 0x3c, 0x90, 0x98, 0x0d, 0x1e, 0xa3, 0xf7, 0x80, 0x38, 0x5a, 0x12, 0xb1, 0xcb, 0xfb, 0x27,
	0xfc, 0x79, 0x10, 0x0a, 0x48, 0x01, 0x47, 0x30, 0x16, 0x04, 0x2a, 0x91, 0x45, 0xdc, 0xd0, 0x43,
	0x98, 0xdb, 0x62, 0x36, 0x0e, 0x84, 0xaa, 0x6d, 0xfc, 0x64, 0x39, 0x05, 0x53, 0x4f, 0x14, 0xd5,
	0x66, 0xa6, 0x7b, 0x33, 0xba, 0x6f, 0x74, 0x03, 0x66, 0xa3, 0x76, 0x79, 0xa8, 0xaf, 0xc1, 0x14,
	0xb2, 0xf1, 0x02, 0x9b, 0xee, 0xb8, 0x8b, 0xa1, 0x37, 0x60, 0xc6, 0x33, 0x31, 0xa6, 0x83, 0x1f,
	0x43, 0x29, 0x58, 0xc1, 0x37, 0x3c, 0x4e, 0xa0, 0x6d, 0xa8, 0x3a, 0xb9, 0x19, 0xbe, 0x72, 0xc6,
	0xda, 0x97, 0x2b, 0x6d, 0xa2, 0xc2, 0x47, 0x5d, 0x64, 0xa1, 0xe2, 0xae, 0xc2, 0xa9, 0x94, 0x5d,
	0xf9, 0xc9, 0xfc, 0x40, 0x80, 0x33, 0x22, 0x33, 0x74, 0xd3, 0x8e, 0x76, 0xa1, 0x63, 0x72, 0xba,
	0x0b, 0x33, 0xa1, 0xb6, 0x80, 0x37, 0xac, 0x19, 0x3f, 0x22, 0x62, 0xd6, 0xcb, 0x7a, 0xe4, 0x9d,
	0x9e, 0xe1, 0x97, 0x6d, 0x1a, 0x0b, 0xce, 0xf1, 0x17, 0x02, 0x2a, 0xf6, 0x6b, 0x11, 0x5c, 0xf2,
	0x9b, 0x69, 0x9c, 0x77, 0xd2, 0xc7, 0x6d, 0x99, 0x11, 0x10, 0x6d, 0xce, 0xf2, 0xf1, 0xe6, 0x6c,
	0x11, 0x4e, 0x30, 0xed, 0xb1, 0x33, 0xe9, 0xb6, 0x9e, 0x4c, 0x7b, 0xcc, 0xa7, 0xe8, 0x37, 0xf1,
	0xae, 0x48, 0x21, 0x9c, 0x16, 0x15, 0xe1, 0x75, 0xa2, 0xf2, 0x4a, 0x80, 0x85, 0x2d, 0x66, 0x77,
	0x86, 0xfd, 0x3e, 0xb3, 0x9c, 0x6f, 0x55, 0xc7, 0xad, 0x9c, 0xe4, 0x87, 0xc2, 0x5c, 0xda, 0x87,
	0xc2, 0xcb, 0x50, 0x36, 0x1d, 0xd3, 0x92, 0x36, 0x1c, 0xec, 0x33, 0x13, 0x23, 0x31, 0x29, 0x96,
	0xdc, 0xd1, 0x36, 0x0e, 0xd2, 0x26, 0xd6, 0x71, 0x84, 0xcf, 0xf1, 0x2b, 0xee, 0x67, 0x02, 0xd4,
	0x1f, 0xca, 0xaa, 0x12, 0x51, 0xe8, 0xb8, 0xf4, 0xde, 0x8d, 0x38, 0x88, 0xad, 0x9e, 0x30, 0xce,
	0xaf, 0xd3, 0x90, 0xff, 0x19, 0x1f, 0x4a, 0xd3, 0xfc, 0xa7, 0x75, 0x38, 0x3f, 0x82, 0x92, 0xa1,
	0x1e, 0xae, 0xec, 0x85, 0xbe, 0xa4, 0x63, 0xb3, 0x5b, 0x81, 0x93, 0x6e, 0xaf, 0x2a, 0x75, 0x1f,
	0x3d, 0x68, 0x55, 0xde, 0xe1, 0x9d, 0xec, 0xe6, 0xee, 0xde, 0x9d, 0x9d, 0x56, 0x45, 0x20, 0xd3,
	0x90, 0xdf, 0x6e, 0x77, 0x2b, 0x39, 0x72, 0x12, 0x4e, 0x6c, 0x6e, 0x77, 0x9a, 0x62, 0xab, 0xdb,
	0xaa, 0xe4, 0xc9, 0x0c, 0x14, 0x9b, 0x1b, 0xdd, 0xd6, 0xd6, 0xae, 0xb8, 0xdd, 0xdc, 0xd8, 0xa9,
	0x4c, 0xac, 0x7c, 0x18, 0xfa, 0xe0, 0xed, 0xf5, 0xd0, 0x5e, 0x0b, 0xfc, 0x0e, 0x5f, 0x7c, 0x7f,
	0xbb, 0xbd, 0x7d, 0x7f, 0xfb, 0x73, 0x6e, 0x93, 0xbf, 0x6d, 0x7c, 0xcd, 0x79, 0xcb, 0x35, 0x7e,
	0x37, 0x07, 0xd3, 0xf7, 0x65, 0x4d, 0xee, 0x33, 0x93, 0xfc, 0x5a, 0x08, 0xf4, 0x3b, 0xf4, 0x5b,
	0x7f, 0x39, 0x16, 0xab, 0xcc, 0x7e, 0xb6, 0x76, 0x65, 0x0c, 0x24, 0xde, 0x08, 0x2f, 0xff, 0xfe,
	0xef, 0x9f, 0xe7, 0xae, 0xd3, 0x25, 0xfc, 0x6b, 0x86, 0xbb, 0xfd, 0x5a, 0x12, 0xbd, 0x1e, 0xea,
	0xf3, 0xc8, 0x2f, 0x05, 0xef, 0x4a, 0x08, 0x71, 0x8b, 0xef, 0x98, 0xd1, 0xf8, 0xd6, 0x2e, 0x1d,
	0x89, 0xe3, 0xbc, 0x6e, 0x21, 0xaf, 0x9b, 0x64, 0x2d, 0xc2, 0x2b, 0x8e, 0x5d, 0x7b, 0x1e, 0x2b,
	0x9a, 0x17, 0xe4, 0xa7, 0x02, 0xaa, 0x79, 0x88, 0x58, 0xfc, 0x93, 0x71, 0x5a, 0xd3, 0x5c, 0xbb,
	0x30, 0x1a, 0xc4, 0x29, 0xbd, 0x8f, 0x94, 0x56, 0xc9, 0xb5, 0x08, 0xa5, 0x08, 0x30, 0x85, 0xcf,
	0x8f, 0x05, 0xbc, 0xd2, 0xa2, 0x1d, 0x28, 0xb9, 0x3a, 0x6a, 0xbb, 0xd0, 0x8d, 0x5a, 0xbb, 0x7c,
	0x34, 0x90, 0x73, 0xbb, 0x82, 0xdc, 0xea, 0xe4, 0x7c, 0x36, 0x37, 0xdc, 0xf7, 0x4f, 0x82, 0x77,
	0x71, 0x24, 0x3e, 0xb1, 0xc5, 0xbf, 0xb6, 0x8e, 0x6c, 0x63, 0x6b, 0x2b, 0x63, 0xa2, 0x39, 0xb9,
	0xcf, 0x90, 0xdc, 0x7a, 0xed, 0xcb, 0x11, 0x72, 0xe9, 0x2b, 0x92, 0x11, 0x5c, 0x17, 0x56, 0xc8,
	0xdf, 0x04, 0x38, 0x3b, 0xaa, 0x03, 0x24, 0x8d, 0x54, 0x3a, 0x23, 0x9b, 0xc1, 0xda, 0x8d, 0x63,
	0xad, 0xe1, 0x8e, 0xdc, 0x45, 0x47, 0x3e, 0xab, 0x7d, 0x9c, 0xe2, 0x48, 0xfa, 0xba, 0x74, 0x77,
	0xfe, 0x2c, 0xc0, 0x62, 0x66, 0x7b, 0x49, 0xd6, 0x92, 0x47, 0x3e, 0xda, 0x91, 0xeb, 0xe3, 0x2f,
	0x08, 0x1d, 0x07, 0xf9, 0x30, 0x9e, 0x2b, 0xe3, 0xba, 0x40, 0x5e, 0x0a, 0x50, 0x8a, 0x74, 0x97,
	0x89, 0x1a, 0x4b, 0xeb, 0x5f, 0x13, 0x35, 0x96, 0xd2, 0xa0, 0x7e, 0x09, 0xb9, 0x5d, 0xa4, 0xb5,
	0x54, 0x39, 0x42, 0xe0, 0xba, 0xd3, 0x78, 0x91, 0xef, 0x09, 0x50, 0x0c, 0xf5, 0xa5, 0xe4, 0x42,
	0xaa, 0xae, 0x44, 0x08, 0x2c, 0x8d, 0x82, 0xf0, 0xed, 0xaf, 0xe3, 0xf6, 0x57, 0xc9, 0xe5, 0x14,
	0xd5, 0x41, 0xd8, 0xda, 0xf3, 0xa0, 0x37, 0x79, 0x41, 0x7e, 0x24, 0xc0, 0xc9, 0x70, 0xbb, 0x4a,
	0x68, 0xf2, 0x24, 0xe2, 0x3d, 0x72, 0xad, 0x3e, 0x12, 0x13, 0xd2, 0x64, 0xf2, 0x6e, 0xfc, 0x80,
	0x7c, 0x5c, 0xca, 0x99, 0xd8, 0x70, 0xc2, 0x43, 0x90, 0xf3, 0x19, 0x5b, 0x78, 0x14, 0xce, 0x66,
	0xce, 0xf3, 0xed, 0x57, 0x70, 0xfb, 0x4b, 0x84, 0xa6, 0x6e, 0x1f, 0x8d, 0xc0, 0x2b, 0x01, 0x66,
	0x13, 0x8d, 0x68, 0x42, 0xdd, 0xb2, 0x1a, 0xe4, 0x84, 0xba, 0x65, 0xf4, 0xb4, 0x6e, 0x56, 0xd4,
	0xce, 0xa7, 0xd4, 0x5d, 0x08, 0xcc, 0x4b, 0xeb, 0x57, 0x02, 0xff, 0xf1, 0x94, 0x6c, 0x3c, 0xc9,
	0x4a, 0x22, 0xf9, 0x32, 0x7b, 0xe4, 0xda, 0xf2, 0x58, 0x58, 0xce, 0xec, 0x1a, 0x32, 0xbb, 0x42,
	0x2f, 0xc4, 0xf2, 0x35, 0x89, 0xe7, 0xe4, 0x5e, 0x39, 0x77, 0x41, 0x8c, 0x59, 0xca, 0x5d, 0x90,
	0x4e, 0xeb, 0xf2, 0xd1, 0xc0, 0x70, 0x0d, 0x25, 0xee, 0x82, 0x24, 0xa1, 0x97, 0x02, 0x94, 0xa3,
	0xfd, 0x1f, 0xb9, 0x94, 0xdc, 0x24, 0xd9, 0xae, 0xd6, 0xe8, 0x11, 0xa8, 0xd0, 0x9d, 0x44, 0xcf,
	0xc4, 0x79, 0x84, 0x90, 0x9c, 0xc4, 0x1f, 0x05, 0x58, 0xcc, 0xec, 0xd5, 0x12, 0x6a, 0x78, 0x54,
	0xa3, 0x99, 0x50, 0xc3, 0xd1, 0x6d, 0x20, 0xbd, 0x89, 0x2c, 0xdf, 0xa5, 0x57, 0x22, 0x2c, 0x33,
	0x17, 0xad, 0x0b, 0x2b, 0x8d, 0xff, 0x08, 0x00, 0x81, 0x0f, 0xe4, 0xf3, 0xff, 0x5d, 0x0c, 0xc9,
	0xf3, 0xff, 0x63, 0x68, 0x1a, 0x33, 0x50, 0x8a, 0xfc, 0xd1, 0x7f, 0x7f, 0x0a, 0xff, 0xc3, 0xe5,
	0xbd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc7, 0xd4, 0x34, 0x1b, 0x23, 0x00, 0x00,
}
