apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
  # rbac for leader-election
resources:
- ../katib-standalone
- leader-election-rbac.yaml
replicas:
- count: 2
  name: katib-controller
configMapGenerator:
- behavior: replace
  files:
  - katib-config.yaml
  name: katib-config
  options:
    disableNameSuffixHash: true
