---
varReference:
  - path: spec/commonName
    kind: Certificate
  - path: spec/dnsNames
    kind: Certificate
  - path: spec/issuerRef/name
    kind: Certificate
  - path: metadata.annotations.cert-manager.io/inject-ca-from
    kind: MutatingWebhookConfiguration
  - path: metadata.annotations.cert-manager.io/inject-ca-from
    kind: ValidatingWebhookConfiguration
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
      - kind: Certificate
        group: cert-manager.io
        path: spec/issuerRef/name
