# coding: utf-8

"""
    Katib

    Swagger description for Katib  # noqa: E501

    The version of the OpenAPI document: v1beta1-0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubeflow.katib.configuration import Configuration


class V1beta1FileSystemPath(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'format': 'str',
        'kind': 'str',
        'path': 'str'
    }

    attribute_map = {
        'format': 'format',
        'kind': 'kind',
        'path': 'path'
    }

    def __init__(self, format=None, kind=None, path=None, local_vars_configuration=None):  # noqa: E501
        """V1beta1FileSystemPath - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._format = None
        self._kind = None
        self._path = None
        self.discriminator = None

        if format is not None:
            self.format = format
        if kind is not None:
            self.kind = kind
        if path is not None:
            self.path = path

    @property
    def format(self):
        """Gets the format of this V1beta1FileSystemPath.  # noqa: E501


        :return: The format of this V1beta1FileSystemPath.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this V1beta1FileSystemPath.


        :param format: The format of this V1beta1FileSystemPath.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def kind(self):
        """Gets the kind of this V1beta1FileSystemPath.  # noqa: E501


        :return: The kind of this V1beta1FileSystemPath.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this V1beta1FileSystemPath.


        :param kind: The kind of this V1beta1FileSystemPath.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def path(self):
        """Gets the path of this V1beta1FileSystemPath.  # noqa: E501


        :return: The path of this V1beta1FileSystemPath.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this V1beta1FileSystemPath.


        :param path: The path of this V1beta1FileSystemPath.  # noqa: E501
        :type: str
        """

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1FileSystemPath):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1FileSystemPath):
            return True

        return self.to_dict() != other.to_dict()
