{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "katib.fullname" . }}-config
  namespace: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.controller.labels" . | nindent 4 }}
data:
  katib-config.yaml: |
{{ .Values.config.katibConfig | indent 4 }}
{{- end }} 