{{- if .Values.controller.leaderElection.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "katib.fullname" . }}-leader-election
  namespace: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "katib.fullname" . }}-leader-election
  namespace: {{ include "katib.namespace" . }}
  labels:
    {{- include "katib.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "katib.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "katib.controller.serviceAccountName" . }}
    namespace: {{ include "katib.namespace" . }}
{{- end }} 