/*
Copyright 2022 The Kubeflow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OptimizationJobSpecApplyConfiguration represents a declarative configuration of the OptimizationJobSpec type for use
// with apply.
type OptimizationJobSpecApplyConfiguration struct {
	Objectives    []ObjectiveApplyConfiguration  `json:"objectives,omitempty"`
	Algorithm     *AlgorithmApplyConfiguration   `json:"algorithm,omitempty"`
	SearchSpace   map[string]string              `json:"searchSpace,omitempty"`
	TrialConfig   *TrialConfigApplyConfiguration `json:"trialConfig,omitempty"`
	TrialTemplate *unnameable_Unsupported        `json:"trialTemplate,omitempty"`
}

// OptimizationJobSpecApplyConfiguration constructs a declarative configuration of the OptimizationJobSpec type for use with
// apply.
func OptimizationJobSpec() *OptimizationJobSpecApplyConfiguration {
	return &OptimizationJobSpecApplyConfiguration{}
}

// WithObjectives adds the given value to the Objectives field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Objectives field.
func (b *OptimizationJobSpecApplyConfiguration) WithObjectives(values ...*ObjectiveApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjectives")
		}
		b.Objectives = append(b.Objectives, *values[i])
	}
	return b
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithAlgorithm(value *AlgorithmApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	b.Algorithm = value
	return b
}

// WithSearchSpace puts the entries into the SearchSpace field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SearchSpace field,
// overwriting an existing map entries in SearchSpace field with the same key.
func (b *OptimizationJobSpecApplyConfiguration) WithSearchSpace(entries map[string]string) *OptimizationJobSpecApplyConfiguration {
	if b.SearchSpace == nil && len(entries) > 0 {
		b.SearchSpace = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SearchSpace[k] = v
	}
	return b
}

// WithTrialConfig sets the TrialConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrialConfig field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithTrialConfig(value *TrialConfigApplyConfiguration) *OptimizationJobSpecApplyConfiguration {
	b.TrialConfig = value
	return b
}

// WithTrialTemplate sets the TrialTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrialTemplate field is set to the value of the last call.
func (b *OptimizationJobSpecApplyConfiguration) WithTrialTemplate(value unnameable_Unsupported) *OptimizationJobSpecApplyConfiguration {
	b.TrialTemplate = &value
	return b
}
