# tensorflow-gpu=2.9.1, cuda=11.7.1
# Ref: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_22-08.html#rel_22-08
FROM nvcr.io/nvidia/tensorflow:22.08-tf2-py3

ENV TARGET_DIR /opt/enas-cnn-cifar10
ENV PYTHONPATH ${TARGET_DIR}

ADD examples/v1beta1/trial-images/enas-cnn-cifar10 ${TARGET_DIR}

WORKDIR  ${TARGET_DIR}

RUN pip install --no-cache-dir scipy==1.8.1
RUN chgrp -R 0 ${TARGET_DIR} \
  && chmod -R g+rwX ${TARGET_DIR}

ENTRYPOINT ["python3", "-u", "RunTrial.py"]
